INSERT INTO CENTR (NOMBRE_CENTR, COMUNIDAD_CENTR, MUNICIPIO_CENTR, CP_CENTR) VALUES
('I.E.S. Alameda de Osuna', 'Comunidad de Madrid', 'Madrid', 28042),
('I.E.S. Alfredo Kraus', 'Comunidad de Madrid', 'Madrid', 28022),
('I.E.S. Antonio Domínguez Ortiz', 'Comunidad de Madrid', 'Madrid', 28038),
('I.E.S. Avenida de los Toreros', 'Comunidad de Madrid', 'Madrid', 28028),
('I.E.S. Beatriz Galindo', 'Comunidad de Madrid', 'Madrid', 28001),
('I.E.S. Blas de Otero', 'Comunidad de Madrid', 'Madrid', 28024),
('I.E.S. Cardenal Herrera Oria', 'Comunidad de Madrid', 'Madrid', 28034),
('I.E.S. Cervantes', 'Comunidad de Madrid', 'Madrid', 28012),
('I.E.S. Ciudad de Jaen', 'Comunidad de Madrid', 'Madrid', 28041),
('I.E.S. Ciudad de los Poetas', 'Comunidad de Madrid', 'Madrid', 28039),
('I.E.S. Conde Orgaz', 'Comunidad de Madrid', 'Madrid', 28043),
('I.E.S. Fortuny', 'Comunidad de Madrid', 'Madrid', 28010),
('I.E.S. Francisco de Goya', 'Comunidad de Madrid', 'Madrid', 28017),
('I.E.S. Francisco de Quevedo', 'Madrid', 'Madrid', 28037),
('I.E.S. Gabriel García Márquez', 'Madrid', 'Madrid', 28033),
('I.E.S. García Morato', 'Madrid', 'Madrid', 28044),
('I.E.S. Gran Capitán', 'Madrid', 'Madrid', 28005),
('I.E.S. Gomez Moreno', 'Madrid', 'Madrid', 28037),
('I.E.S. Isaac Newton', 'Madrid', 'Madrid', 28035),
('I.E.S. Joaquín Rodrigo', 'Madrid', 'Madrid', 28032),
('I.E.S. Joaquín Turina', 'Madrid', 'Madrid', 28003),
('I.E.S. Juan de la Cierva', 'Madrid', 'Madrid', 28005),
('I.E.S. Juan de Castilla', 'Madrid', 'Madrid', 28030),
('I.E.S. La Estrella', 'Madrid', 'Madrid', 28007),
('I.E.S. Lope de Vega', 'Madrid', 'Madrid', 28015),
('I.E.S. Manuel Fraga Iribarne', 'Madrid', 'Madrid', 28050),
('I.E.S. Mariano José de Larra', 'Madrid', 'Madrid', 28047),
('I.E.S. María Rodrigo', 'Madrid', 'Madrid', 28051),
('I.E.S. Mirasierra', 'Madrid', 'Madrid', 28034),
('I.E.S. Nuestra Señora de la Almudena', 'Madrid', 'Madrid', 28039),
('I.E.S. Pedro Salines', 'Madrid', 'Madrid', 28026),
('I.E.S. Príncipe Felipe', 'Madrid', 'Madrid', 28029),
('I.E.S. Ramiro de Maeztu', 'Madrid', 'Madrid', 28006),
('I.E.S. Ramón y Cajal', 'Madrid', 'Madrid', 28050),
('I.E.S. Rey Pastor', 'Madrid', 'Madrid', 28030),
('I.E.S. San Cristobal de los Ángeles', 'Madrid', 'Madrid', 28021),
('I.E.S. San Isidro', 'Madrid', 'Madrid', 28005),
('I.E.S. San Juan Bautista', 'Madrid', 'Madrid', 28043),
('I.E.S. Santamarta', 'Madrid', 'Madrid', 28016),
('I.E.S. Tirso de Molina', 'Madrid', 'Madrid', 28038),
('I.E.S. Valdebernardo', 'Madrid', 'Madrid', 28032),
('I.E.S. Villa de Vallecas', 'Madrid', 'Madrid', 28031),
('I.E.S. Villablanca', 'Madrid', 'Madrid', 28032);


INSERT INTO CURSO (NIVEL_CURSO, GRADO_CURSO, LETRA_CURSO, ID_CENTR) VALUES
(1, 'E. S. O.', 'A', 1),
(2, 'E. S. O.', 'A', 1),
(3, 'E. S. O.', 'A', 1),
(4, 'E. S. O.', 'A', 1),
(1, 'E. S. O.', 'B', 1),
(2, 'E. S. O.', 'B', 1),
(3, 'E. S. O.', 'B', 1),
(4, 'E. S. O.', 'B', 1),
(1, 'E. S. O.', 'A', 2),
(2, 'E. S. O.', 'A', 2),
(3, 'E. S. O.', 'A', 2),
(4, 'E. S. O.', 'A', 2),
(1, 'E. S. O.', 'B', 2),
(2, 'E. S. O.', 'B', 2),
(3, 'E. S. O.', 'B', 2),
(4, 'E. S. O.', 'B', 2),
(1, 'E. S. O.', 'A', 3),
(2, 'E. S. O.', 'A', 3),
(3, 'E. S. O.', 'A', 3),
(4, 'E. S. O.', 'A', 3),
(1, 'E. S. O.', 'B', 3),
(2, 'E. S. O.', 'B', 3),
(3, 'E. S. O.', 'B', 3),
(4, 'E. S. O.', 'B', 3),
(1, 'E. S. O.', 'A', 4),
(2, 'E. S. O.', 'A', 4),
(3, 'E. S. O.', 'A', 4),
(4, 'E. S. O.', 'A', 4),
(1, 'E. S. O.', 'B', 4),
(2, 'E. S. O.', 'B', 4),
(3, 'E. S. O.', 'B', 4),
(4, 'E. S. O.', 'B', 4),
(1, 'E. S. O.', 'A', 5),
(2, 'E. S. O.', 'A', 5),
(3, 'E. S. O.', 'A', 5),
(4, 'E. S. O.', 'A', 5),
(1, 'E. S. O.', 'B', 5),
(2, 'E. S. O.', 'B', 5),
(3, 'E. S. O.', 'B', 5),
(4, 'E. S. O.', 'B', 5),
(1, 'E. S. O.', 'A', 6),
(2, 'E. S. O.', 'A', 6),
(3, 'E. S. O.', 'A', 6),
(4, 'E. S. O.', 'A', 6),
(1, 'E. S. O.', 'B', 6),
(2, 'E. S. O.', 'B', 6),
(3, 'E. S. O.', 'B', 6),
(4, 'E. S. O.', 'B', 6),
(1, 'E. S. O.', 'A', 7),
(2, 'E. S. O.', 'A', 7),
(3, 'E. S. O.', 'A', 7),
(4, 'E. S. O.', 'A', 7),
(1, 'E. S. O.', 'B', 7),
(2, 'E. S. O.', 'B', 7),
(3, 'E. S. O.', 'B', 7),
(4, 'E. S. O.', 'B', 7),
(1, 'E. S. O.', 'A', 8),
(2, 'E. S. O.', 'A', 8),
(3, 'E. S. O.', 'A', 8),
(4, 'E. S. O.', 'A', 8),
(1, 'E. S. O.', 'B', 8),
(2, 'E. S. O.', 'B', 8),
(3, 'E. S. O.', 'B', 8),
(4, 'E. S. O.', 'B', 8),
(1, 'E. S. O.', 'A', 9),
(2, 'E. S. O.', 'A', 9),
(3, 'E. S. O.', 'A', 9),
(4, 'E. S. O.', 'A', 9),
(1, 'E. S. O.', 'B', 9),
(2, 'E. S. O.', 'B', 9),
(3, 'E. S. O.', 'B', 9),
(4, 'E. S. O.', 'B', 9),
(1, 'E. S. O.', 'A', 10),
(2, 'E. S. O.', 'A', 10),
(3, 'E. S. O.', 'A', 10),
(4, 'E. S. O.', 'A', 10),
(1, 'E. S. O.', 'B', 10),
(2, 'E. S. O.', 'B', 10),
(3, 'E. S. O.', 'B', 10),
(4, 'E. S. O.', 'B', 10),
(1, 'E. S. O.', 'A', 11),
(2, 'E. S. O.', 'A', 11),
(3, 'E. S. O.', 'A', 11),
(4, 'E. S. O.', 'A', 11),
(1, 'E. S. O.', 'B', 11),
(2, 'E. S. O.', 'B', 11),
(3, 'E. S. O.', 'B', 11),
(4, 'E. S. O.', 'B', 11),
(1, 'E. S. O.', 'A', 12),
(2, 'E. S. O.', 'A', 12),
(3, 'E. S. O.', 'A', 12),
(4, 'E. S. O.', 'A', 12),
(1, 'E. S. O.', 'B', 12),
(2, 'E. S. O.', 'B', 12),
(3, 'E. S. O.', 'B', 12),
(4, 'E. S. O.', 'B', 12),
(1, 'E. S. O.', 'A', 13),
(2, 'E. S. O.', 'A', 13),
(3, 'E. S. O.', 'A', 13),
(4, 'E. S. O.', 'A', 13),
(1, 'E. S. O.', 'B', 13),
(2, 'E. S. O.', 'B', 13),
(3, 'E. S. O.', 'B', 13),
(4, 'E. S. O.', 'B', 13);


INSERT INTO ALUMN (NOMBRE_ALUMN, APELLIDO_ALUMN, EMAIL_ALUMN, CONTRASENA_ALUMN, EXPERIENCIA_ALUMN, PUNTOS_ALUMN, IMG_ALUMN, ID_CURSO) VALUES
('Lola', 'Pérez', 'lolaperez@gmail.com', 'cont5678', 4, 1200, '../img/alumno1.jpg', 1),
('Raúl', 'González', 'raulitog@gmail.com', 'cont5678', 6, 1520, '../img/alumno2.jpg', 1),
('Elena', 'Rodríguez', 'e.rodriguez@gmail.com', 'cont5678', 7, 800, '../img/alumno3.jpg', 1),
('María', 'Alonso', 'maria.alonso@gmail.com', 'cont5678', 3, 1654, '../img/alumno4.jpg', 1),
('Roberto', 'García', 'robertoG@gmail.com', 'cont5678', 8, 1935, '../img/alumno5.jpg', 1),

('Álvaro', 'Sánchez', 'a.sanchez1@gmail.com', 'cont5678', 8, 1735, '../img/alumno6.jpg', 2),
('Sofía', 'Santos', 'sofiasantos@gmail.com', 'cont5678', 6, 1408, '../img/alumno7.jpg', 2),
('Adrián', 'Martínez', 'a.martinez@gmail.com', 'cont5678', 4, 1735, '../img/alumno8.jpg', 2),
('Mario', 'Pascual', 'marioPascual@gmail.com', 'cont5678', 5, 1103, '../img/alumno9.jpg', 2),

('Lola', 'Pérez', 'lolaperez@gmail.com', 'cont5678', 7, 1200, '../img/alumno1.jpg', 3),
('Raúl', 'González', 'raulitog@gmail.com', 'cont5678', 6, 1520, '../img/alumno2.jpg', 3),
('Elena', 'Rodríguez', 'e.rodriguez@gmail.com', 'cont5678', 4, 800, '../img/alumno3.jpg', 3),
('María', 'Alonso', 'maria.alonso@gmail.com', 'cont5678', 3, 1654, '../img/alumno4.jpg', 3),
('Roberto', 'García', 'robertoG@gmail.com', 'cont5678', 5, 1935, '../img/alumno5.jpg', 3),

('Lola', 'Pérez', 'lolaperez@gmail.com', 'cont5678', 7, 1200, '../img/alumno1.jpg', 4),
('Raúl', 'González', 'raulitog@gmail.com', 'cont5678', 6, 1520, '../img/alumno2.jpg', 4),
('Elena', 'Rodríguez', 'e.rodriguez@gmail.com', 'cont5678', 4, 800, '../img/alumno3.jpg', 4),
('María', 'Alonso', 'maria.alonso@gmail.com', 'cont5678', 3, 1654, '../img/alumno4.jpg', 4),
('Roberto', 'García', 'robertoG@gmail.com', 'cont5678', 5, 1935, '../img/alumno5.jpg', 4),

('Lola', 'Pérez', 'lolaperez@gmail.com', 'cont5678', 7, 1200, '../img/alumno1.jpg', 5),
('Raúl', 'González', 'raulitog@gmail.com', 'cont5678', 6, 1520, '../img/alumno2.jpg', 5),
('Elena', 'Rodríguez', 'e.rodriguez@gmail.com', 'cont5678', 4, 800, '../img/alumno3.jpg', 5),
('María', 'Alonso', 'maria.alonso@gmail.com', 'cont5678', 3, 1654, 'w../img/alumno4.jpg', 5),
('Roberto', 'García', 'robertoG@gmail.com', 'cont5678', 5, 1935, '../img/alumno5.jpg', 5),

('Lola', 'Pérez', 'lolaperez@gmail.com', 'cont5678', 7, 1200, '../img/alumno1.jpg', 6),
('Raúl', 'González', 'raulitog@gmail.com', 'cont5678', 6, 1520, 'w../img/alumno2.jpg', 6),
('Elena', 'Rodríguez', 'e.rodriguez@gmail.com', 'cont5678', 4, 800, '../img/alumno3.jpg', 6),
('María', 'Alonso', 'maria.alonso@gmail.com', 'cont5678', 3, 1654, '../img/alumno4.jpg', 6),
('Roberto', 'García', 'robertoG@gmail.com', 'cont5678', 5, 1935, '../img/alumno5.jpg', 6),

('Lola', 'Pérez', 'lolaperez@gmail.com', 'cont5678', 7, 1200, '../img/alumno1.jpg', 7),
('Raúl', 'González', 'raulitog@gmail.com', 'cont5678', 6, 1520, '../img/alumno2.jpg', 7),
('Elena', 'Rodríguez', 'e.rodriguez@gmail.com', 'cont5678', 4, 800, '../img/alumno3.jpg', 7),
('María', 'Alonso', 'maria.alonso@gmail.com', 'cont5678', 3, 1654, '../img/alumno4.jpg', 7),
('Roberto', 'García', 'robertoG@gmail.com', 'cont5678', 5, 1935, '../img/alumno5.jpg', 7),

('Lola', 'Pérez', 'lolaperez@gmail.com', 'cont5678', 7, 1200, '../img/alumno1.jpg', 8),
('Raúl', 'González', 'raulitog@gmail.com', 'cont5678', 6, 1520, '../img/alumno2.jpg', 8),
('Elena', 'Rodríguez', 'e.rodriguez@gmail.com', 'cont5678', 4, 800, '../img/alumno3.jpg', 8),
('María', 'Alonso', 'maria.alonso@gmail.com', 'cont5678', 3, 1654, '../img/alumno4.jpg', 8),
('Roberto', 'García', 'robertoG@gmail.com', 'cont5678', 5, 1935, '../img/alumno5.jpg', 8),

('Lola', 'Pérez', 'lolaperez@gmail.com', 'cont5678', 7, 1200, '../img/alumno1.jpg', 9),
('Raúl', 'González', 'raulitog@gmail.com', 'cont5678', 6, 1520, '../img/alumno2.jpg', 9),
('Elena', 'Rodríguez', 'e.rodriguez@gmail.com', 'cont5678', 4, 800, '../img/alumno3.jpg', 9),
('María', 'Alonso', 'maria.alonso@gmail.com', 'cont5678', 3, 1654, '../img/alumno4.jpg', 9),
('Roberto', 'García', 'robertoG@gmail.com', 'cont5678', 5, 1935, '../img/alumno5.jpg', 9),

('Lola', 'Pérez', 'lolaperez@gmail.com', 'cont5678', 7, 1200, '../img/alumno1.jpg', 10),
('Raúl', 'González', 'raulitog@gmail.com', 'cont5678', 6, 1520, '../img/alumno2.jpg', 10),
('Elena', 'Rodríguez', 'e.rodriguez@gmail.com', 'cont5678', 4, 800, '../img/alumno3.jpg', 10),
('María', 'Alonso', 'maria.alonso@gmail.com', 'cont5678', 3, 1654, '../img/alumno4.jpg', 10),
('Roberto', 'García', 'robertoG@gmail.com', 'cont5678', 5, 1935, '../img/alumno5.jpg', 10);


INSERT INTO PROFE (NOMBRE_PROFE, APELLIDO_PROFE, EMAIL_PROFE, CONTRASENA_PROFE, IMG_PROFE, ID_CENTR) VALUES
('Alfonso', 'Muñoz', 'alfonsomuñoz@gmail.com', 'cont5678', '../img/profe1.jpg', 1),
('Emilia', 'HernÁndez', 'e.Hernandez@gmail.com', 'cont5678', '../img/profe2.jpg', 1),
('Gabriel', 'Márquez', 'gabrielMarquez@gmail.com', 'cont5678', '../img/profe3.jpg', 1),

('Isabel', 'Ordóñez', 'IsabelOrdoñez@gmail.com', 'cont5678', '../img/profe4.jpeg', 2),
('Laura', 'Cañizares', 'LauraCañizares@gmail.com', 'cont5678', '../img/profe5.jpg', 2),
('Saúl', 'Ortega', 'saul.ortega@gmail.com', 'cont5678', '../img/profe6.jpg', 2),

('César', 'García', 'cesargarcia@gmail.com', 'cont5678', 'w../img/profe7.jpg', 3),
('Manuel', 'Santamarta', 'm.Santamarta@gmail.com', 'cont5678', '../img/profe8.jpg', 3),
('Clara', 'Laguna', 'LagunaClara@gmail.com', 'cont5678', '../img/profe9.jpg', 3),
('Esteban', 'Calvo', 'estebancalvo@gmail.com', 'cont5678', '../img/profe10.jpg', 3);


INSERT INTO ASIGN (NOMBRE_ASIGN, ID_PROFE) VALUES
('Lengua castellana y literatura', 1),
('Inglés', 1),
('Matemáticas', 2),
('Biología y Geología', 2),
('Física y Química', 2),
('Ciencias Sociales', 3),
('Música', 3),
('Matemáticas', 4),
('Biología y Geología', 4),
('Lengua castellana y literatura', 5),
('Valores Éticos', 5),
('Matemáticas', 6),
('Tecnología', 6),
('Educación Física', 7),
('Biología y Geología', 7),
('Educación plástica y audiovisual', 8),
('Lengua Castellana y Literatura', 9),
('Latín', 9),
('Economía', 10),
('Matemáticas', 10),
('Educación para la ciudadanía', 10),
('Inglés', 3),
('Inglés', 7),
('Inglés', 8),
('Ciencias Sociales', 5),
('Ciencias Sociales', 6);


INSERT INTO TEMAS (NOMBRE_TEMAS, TRIMESTRE_TEMAS, ORDEN_TEMAS, ID_ASIGN) VALUES
/* LENGUA */
('El lenguaje literario', 1, 1, 1),
('La narración, el lenguaje oral/ escrito, primitivas, derivadas y géneros literarios', 1, 2, 1),
('Género nominal, sustantivos. Escribir carta y épica castellana', 1, 3, 1),
('Descripción. Adjetivos, forma y uso', 1, 4, 1),
('El predicado. Clases y complementos', 1, 5, 1),
('Oración simple y compuesta', 1, 6, 1),
('Clases de textos', 1, 7, 1),

('Descripción. Adjetivos forma y uso', 2, 8, 1),
('Textos expositivos', 2, 9, 1),
('Cuento, novela y resumen', 2, 10, 1),
('El determinante. Rima, verso, esquema', 2, 11, 1),
('Pronombres. clasificación. Palabras compuestas. Lírica', 2, 12, 1),
('Adverbio', 2, 13, 1),
('Diálogo y sinónimos', 2, 14, 1),

('Concepto de oración', 3, 15, 1),
('Imperativas, desiderativas y dubitativas', 3, 16, 1),
('El lenguaje y oración gramatical', 3, 17, 1),
('El informe, los determinantes, función y clases. Lexemas y morfemas. Lírica', 3, 18, 1),
('Los complementos, clases, sufijos. El folleto informativo. Lírica: la estrofa y el poema', 3, 19, 1),
('Los pronombres. Clases. El texto instructivo. Lírica: serranilla, oda y el poema', 3, 20, 1),

/* LENGUA */
('El sintagma verbal. Formas. Morfemas flexivos. Los impresos. La épica', 1, 1, 10),
('El predicado. Clases y complementos', 1, 2, 10),
('El debate', 1, 3, 10),
('La oración compuesta. Sinónima y antonimia. La coma y el guión y paréntesis. Teatro y las figuras literarias', 1, 4, 10),
('Lengua y sociedad', 1, 5, 10),
('Las palabras', 1, 6, 10),
('La oración', 1, 7, 10),
('Oración simple y compuesta', 1, 8, 10),

('Clases de textos', 2, 9, 10),
('La literatura', 2, 10, 10),
('Edad Media', 2, 11, 10),
('Siglo XV', 2, 12, 10),
('El Renacimiento', 2, 13, 10),
('El Barroco', 2, 14, 10),
('El teatro', 2, 15, 10),
('Siglo XVIII', 2, 16, 10),

('El siglo XVIII: el Neoclasicismo', 3, 17, 10),
('Romanticismo', 3, 18, 10),
('Realismo', 3, 19, 10),
('Modernismo', 3, 20, 10),
('Generación del 98', 3, 21, 10),
('Vanguardias', 3, 22, 10),
('Generación del 27', 3, 23, 10),

/* SOCIALES */
('Prehistoria: el Paleolítico', 1, 1, 6),
('Neolítico y Edad de los metales', 1, 2, 6),
('Mesopotamia y primeras civilizaciones', 1, 3, 6),
('Antiguo Egipto', 1, 4, 6),
('Grecia antigua', 1, 5, 6),
('Roma antigua', 1, 6, 6),

('Hispania romana', 2, 7, 6),
('La Tierra en el universo', 2, 8, 6),
('La representación de la Tierra y las coordenadas', 2, 9, 6),
('Geografía física: relieve continental y océano mundial', 2, 10, 6),
('Hidrografía: los ríos y el relieve', 2, 11, 6),
('Tiempo y clima', 2, 12, 6),

('Climas y paisajes naturales', 3, 13, 6),
('Tiempo y clima en España', 3, 14, 6),
('Imperio bizantino y carolingio', 3, 15, 6),
('El Islam y el Al-Andalus', 3, 16, 6),
('Cronología de la Edad Media', 3, 17, 6),
('Las invasiones bárbaras', 3, 18, 6),

/* SOCIALES */
('Carlomagno y su imperio', 1, 1, 25),
('La Europa feudal', 1, 2, 25),
('El renacer urbano de Europa', 1, 3, 25),
('Los descubrimientos', 1, 4, 25),
('El nacimiento del Estado moderno', 1, 5, 25),
('El Renacimiento', 1, 6, 25),

('Reforma y Contrarreforma', 2, 7, 25),
('Los Reyes Católicos', 2, 8, 25),
('El arte renacentista', 2, 9, 25),
('El siglo XVII', 2, 10, 25),
('La población', 2, 11, 25),
('El mapa físico de la Tierra', 2, 12, 25),

('El mapa físico de España', 3, 13, 25),
('La población en el mundo actual', 3, 14, 25),
('Las ciudades en el mundo actual', 3, 15, 25),
('La actividad económica y el trabajo', 3, 16, 25),
('Las actividades del sector primario', 3, 17, 25),
('Las actividades y los espacios industriales', 3, 18, 25),

/* SOCIALES */
('Las actividades terciarias y su transformación', 1, 1, 26),
('La economía de España', 1, 2, 26),
('Los impactos medioambientales', 1, 3, 26),
('La organización política de las sociedades', 1, 4, 26),
('Desigualdades económicas y sociales', 1, 5, 26),
('Introducción a la Historia', 1, 6, 26),

('Los inicios del siglo XVIII', 2, 7, 26),
('El liberalismo', 2, 8, 26),
('Revolución Industrial', 2, 9, 26),
('España en el siglo XIX', 2, 10, 26),
('Imperialismo y Primera Guerra Mundial', 2, 11, 26),
('Periodo de entreguerras', 2, 12, 26),

('España (1898-1975)', 3, 13, 26),
('La Segunda Guerra Mundial', 3, 14, 26),
('De la Guerra Fría al nuevo orden', 3, 15, 26),
('La España reciente', 3, 16, 26),
('Globalización y nuevo orden internacional', 3, 17, 26),

/* MATEMÁTICAS */
('Números naturales', 1, 1, 3),
('Divisibilidad', 1, 2, 3),
('Números enteros', 1, 3, 3),
('Números decimales', 1, 4, 3),
('Fracciones', 1, 5, 3),
('Proporcionalidad', 1, 6, 3),
('Sistema métrico decimal', 1, 7, 3),
('Elementos del plano', 1, 8, 3),
('Polígonos', 1, 9, 3),

('Áreas de las figuras planas', 2, 10, 3),
('Circunferencia y círculo', 2, 11, 3),
('Gráficas y funciones', 2, 12, 3),
('Potencias y radicales', 2, 13, 3),
('Fracciones', 2, 14, 3),
('Números decimales', 2, 15, 3),
('Proporcionalidad', 2, 16, 3),
('Expresiones algebraicas', 2, 17, 3),

('Ecuaciones', 3, 18, 3),
('Semejanza y teorema de Thales', 3, 19, 3),
('Volumen de cuerpos geométricos', 3, 20, 3),
('Funciones', 3, 21, 3),
('Estadística', 3, 22, 3),
('Números reales', 3, 23, 3),
('Potencias y radicales', 3, 24, 3),
('Expresiones algebraicas', 3, 25, 3),

/* MATEMÁTICAS */
('Ecuaciones', 1, 1, 8),
('Sistema de ecuaciones', 1, 2, 8),
('Sucesiones y progresiones', 1, 3, 8),
('Concepto de función', 1, 4, 8),
('Funciones elementales', 1, 5, 8),
('Teoremas de Thales y Pitágoras', 1, 6, 8),
('Problemas geométricos', 1, 7, 8),
('Tablas y gráficos estadísticos', 1, 8, 8),
('Parámetros estadísticos', 1, 9, 8),

('Cálculo de probabilidades', 2, 10, 8),
('Movimientos', 2, 11, 8),
('Números reales', 2, 12, 8),
('Radicales', 2, 13, 8),
('Polinomios y fracciones algebraicas', 2, 14, 8),
('Ecuaciones y sistemas de ecuaciones no lineales', 2, 15, 8),
('Inecuaciones', 2, 16, 8),
('Conceptos básicos de funciones', 2, 17, 8),
('Representación gráfica de parábolas e hipérbolas', 2, 18, 8),

('Representar raíces, exponenciales y definidas a trozos', 3, 19, 8),
('Estadística. Estudio de una variable', 3, 20, 8),
('Combinatoria', 3, 21, 8),
('Probabilidad. Conceptos básicos', 3, 22, 8),
('Trigonometría: razones trigonométricas', 3, 23, 8),
('Triángulos rectángulos', 3, 24, 8),
('Vectores en el plano', 3, 25, 8),
('Ecuaciones de la recta en el plana', 3, 26, 8),

/* INGLÉS */
('Present simple', 1, 1, 2),
('Present simple vs present continuos', 1, 2, 2),
('This is/are', 1, 3, 2),
('Quantifiers and uncountable', 1, 4, 2),
('Adverbs of frequency', 1, 5, 2),
('Questions words', 1, 6, 2),
('Subject questions', 1, 7, 2),
('Comparatives', 1, 8, 2),

('Past simple', 2, 9, 2),
('Irregular verbs', 2, 10, 2),
('Modal verbs of obligation', 2, 11, 2),
('Imperatives', 2, 12, 2),
('Be going to', 2, 13, 2),
('Present continuos with a future meaning', 2, 14, 2),
('Will', 2, 15, 2),

('Will or be going to', 3, 16, 2),
('First conditonal', 3, 17, 2),
('Past simple and past continuos', 3, 18, 2),
('Infinitive of purpose', 3, 19, 2),
('Present simple and continuos with future meaning', 3, 20, 2),
('Present continuos and be going to', 3, 21, 2),
('Future: going to or will', 3, 22, 2),

/* INGLÉS */
('Adjetives + prepositions', 1, 1, 22),
('Adjetives: -ed y -ing', 1, 2, 22),
('All, half, most and none', 1, 3, 22),
('Enough and too', 1, 4, 22),
('A few, few, a litlle and little', 1, 5, 22),
('Present perfect: already, just, still and yet', 1, 6, 22),
('Present perfect: for and since', 1, 7, 22),
('Present perfect: been and gone', 1, 8, 22),

('Present perfect: ever and never', 2, 9, 22),
('First conditional', 2, 10, 22),
('Second conditional', 2, 11, 22),
('Modal verbs of ability', 2, 12, 22),
('Modal verbs of obligation', 2, 13, 22),
('Modal verbs of advice', 2, 14, 22),
('Defining relative clauses', 2, 15, 22),

('When to omit the relative pronoun', 3, 16, 22),
('Phrasal verbs', 3, 17, 22),
('Passive', 3, 18, 22),
('Be and have got', 3, 19, 22),
('Can/can not', 3, 20, 22),
('Present continuos', 3, 21, 22),
('Present simple', 3, 22, 22),

/* INGLÉS */
('Present simple vs present continuos', 1, 1, 23),
('Frequency adverbs', 1, 2, 23),
('Past simple', 1, 3, 23),
('Time expressions', 1, 4, 23),
('Sequencing words', 1, 5, 23),
('Past continuos', 1, 6, 23),
('Past simple vs past continuos', 1, 7, 23),
('Suggestions', 1, 8, 23),

('Connectors', 2, 9, 23),
('Have to', 2, 10, 23),
('Some/any', 2, 11, 23),
('Much/many/a lot of', 2, 12, 23),
('Invitations', 2, 13, 23),
('Comparatives + than', 2, 14, 23),
('Superlatives + in', 2, 15, 23),
('Too/enough + adjective', 2, 16, 23),

('And y but', 3, 17, 23),
('Prensent perfect affirmative and negative', 3, 18, 23),
('Present perfect with just', 3, 19, 23),
('Present perfect interrogative', 3, 20, 23),
('Will', 3, 21, 23),
('First condicional', 3, 22, 23),
('Present simple vs present continuos', 3, 23, 23),
('Like/enjoy/hate', 3, 24, 23),

/* INGLÉS */
('Adverbs of frequency', 1, 1, 24),
('Questions forms', 1, 2, 24),
('Past simple', 1, 3, 24),
('Past simple vs past continuos', 1, 4, 24),
('Used to + infinitive', 1, 5, 24),
('Connectors', 1, 6, 24),
('Present perfect', 1, 7, 24),
('For/since/just/already/yet', 1, 8, 24),

('Present perfect vs past simple', 2, 9, 24),
('Future with going to', 2, 10, 24),
('Future with will', 2, 11, 24),
('Future with present continuos', 2, 12, 24),
('Expressing probability with may/might', 2, 13, 24),
('Questions forms', 2, 14, 24),
('Time clauses', 2, 15, 24),
('First conditional', 2, 16, 24),

('Unless', 3, 17, 24),
('Adverbs of manner', 3, 18, 24),
('Second conditional', 3, 19, 24),
('Should/should not', 3, 20, 24),
('Deffing relative clauses', 3, 21, 24),
('The pasive', 3, 22, 24),
('Reflexive pronouns', 3, 23, 24),
('Reported speech', 3, 24, 24),

/* EDUCACIÓN FISICA */
('Calentamiento general', 1, 1, 14),
('Las capacidades físicas básicas', 1, 2, 14),
('Habilidades motrices básicas', 1, 3, 14),
('Iniciación al badminton', 1, 4, 14),
('Iniciación al balonmano ', 1, 5, 14),
('Iniciación a las técnicas de atletismo', 1, 6, 14),

('Calentamientos motores', 2, 7, 14),
('Nos ponemos en forma', 2, 8, 14),
('Hábitos negativos', 2, 9, 14),
('Quiero ser un buen deportista', 2, 10, 14),
('Leer y exponer', 2, 11, 14),
('Judo', 2, 12, 14),
('Tenis', 2, 13, 14),
('Jugamos otros deportes', 2, 14, 14),
('El Circo del Sol', 2, 15, 14),

('Ejercicio físico, condición física y salud', 3, 16, 14),
('Frecuencia cardiaca', 3, 17, 14),
('Calentamiento', 3, 18, 14),
('Práctica de un deporte habitual', 3, 19, 14),
('Juegos y deportes alternativos', 3, 20, 14),
('Forma diferente de hacer gimnasia', 3, 21, 14),
('Nutrición, salud y ejercicio físico', 3, 22, 14),
('Respiración y relajación', 3, 23, 14),

/* BIOLOGÍA Y GEOLOGÍA */
('La Tierra en el universo', 1, 1, 4),
('La geosfera', 1, 2, 4),
('Los minerales y las rocas', 1, 3, 4),
('La atmósfera', 1, 4, 4),
('La hidrosfera', 1, 5, 4),
('La vida en la Tierra', 1, 6, 4),
('Clasificación de los seres vivos', 1, 7, 4),

('Invertebrados', 2, 8, 4),
('Vertebrados', 2, 9, 4),
('Las plantas', 2, 10, 4),
('Los ecosistemas', 2, 11, 4),
('Metodología científica', 2, 12, 4),
('Organización general del cuerpo humano', 2, 13, 4),
('Alimentación y salud', 2, 14, 4),

('El aparato digestivo y la disgestión', 3, 15, 4),
('El aparato respiratorio y la respiración', 3, 16, 4),
('Aparato circulatorio y circulación', 3, 17, 4),
('El aparato excretor y la excreción', 3, 18, 4),
('El sistema nervioso', 3, 19, 4),
('El sistema endocrino', 3, 20, 4),

/* BIOLOGÍA Y GEOLOGÍA */
('Órganos receptores. Órganos de los sentidos', 1, 1, 9),
('Órganos efectores. Órganos de los sentidos', 1, 2, 9),
('Sexualidad y reproducción humanas', 1, 3, 9),
('La salud y la enfermedad', 1, 4, 9),
('Los ecosistemas', 1, 5, 9),
('La actividad geológica externa del planeta Tierra', 1, 6, 9),
('La actividad geología interna del planeta Tierra', 1, 7, 9),

('El tiempo geológico', 2, 8, 9),
('Historia de la Tierra', 2, 9, 9),
('La dinámica terrestre', 2, 10, 9),
('La técnica de placas', 2, 11, 9),
('La célula', 2, 12, 9),
('La herencia genética', 2, 13, 9),

('Genética humana', 3, 14, 9),
('La ingeniería genética', 3, 15, 9),
('Origen y evolución de los seres vivos', 3, 16, 9),
('Dinámica de los ecosistemas', 3, 17, 9),
('Dinámica de las comunidades', 3, 18, 9),
('La humanidad y el medio ambiente', 3, 19, 9),

/* MÚSICA */
('Introducción', 1, 1, 7),
('La altura: definición y tipos de sonidos', 1, 2, 7),
('El pentagrama y las notas musicales', 1, 3, 7),
('La clave', 1, 4, 7),
('Las líneas adicionales', 1, 5, 7),

('Las alteraciones', 2, 6, 7),
('El sonido y sus cualidades', 2, 7, 7),
('Elementos que intervienen en la audición', 2, 8, 7),
('Las cuatro cualidades del sonido', 2, 9, 7),

('La altura', 3, 10, 7),
('La duración', 3, 11, 7),
('La intensidad', 3, 12, 7),
('El timbre', 3, 13, 7),

/* VALORES ÉTICOS */
('La dignidad de la persona', 1, 1, 11),
('La comprensión, el respeto y la igualdad en las relaciones humanas', 1, 2, 11),
('La reflexión ética', 1, 3, 11),
('Los valores éticos, el derecho y los derechos humanos', 1, 4, 11),

('La dignidad de la persona', 2, 5, 11),
('Comprensión respeto e igualdad', 2, 6, 11),
('La reflexión ética', 2, 7, 11),

('Justicia y política', 3, 8, 11),
('Derechos humanos', 3, 9, 11),
('Valores éticos, ciencia y tecnología', 3, 10, 11),

/* FISICA Y QUIMICA */
('La actividad científica', 1, 1, 5),
('Como trabajan los científicos', 1, 2, 5),
('Estados de agregación', 1, 3, 5),
('Los cambios en la materia', 1, 4, 5),
('Formulación', 1, 5, 5),
('El movimiento y la fuerza', 1, 6, 5),
('La energia', 1, 7, 5),

('Método científico', 2, 8, 5),
('Estados de la materia y teoría científica', 2, 9, 5),
('Sustancias puras y mezclas', 2, 10, 5),
('El átomo y los elementos químicos', 2, 11, 5),
('Los elementos y compuestos químicos', 2, 12, 5),
('Reacciones químicas', 2, 13, 5),
('El movimiento rectilíneo', 2, 14, 5),
('Movimiento circular', 2, 15, 5),

('Las fuerzas', 3, 16, 5),
('Fuerzas y presiones en fluidos', 3, 17, 5),
('Astronomía y gravitación universal', 3, 18, 5),
('Trabajo y energía', 3, 19, 5),
('Calor y energía', 3, 20, 5),
('Las ondas', 3, 21, 5),
('Estructura de átomo y enlaces químicos', 3, 22, 5),
('Transformación química', 3, 23, 5),
('La química del carbono', 3, 24, 5),
('Compuestos de carbono', 3, 25, 5),

/* EDUCACIÓN PLÁSTICA Y AUDIOVISUAL */
('Lugares geométricos', 1, 1, 16),
('Las texturas', 1, 2, 16),

('Tangencias', 2, 3, 16),
('Relaciones entre formas', 2, 4, 16),
('Composiciones de formas modulares', 2, 5, 16),

('El color', 3, 6, 16),
('Diseño gráfico', 3, 7, 16),

/* TECNOLOGÍA */
('Dibujo', 1, 1, 13),
('La madera', 1, 2, 13),

('Metales', 2, 3, 13),
('Estructuras', 2, 4, 13),

('Electricidad', 3, 5, 13),
('Informática', 3, 6, 13),

/* LATÍN */
('El origen del latín y su diversificación', 1, 1, 18),
('La lengua latina y su evolución', 1, 2, 18),
('Introducción a la lengua latina', 1, 3, 18),

('Primera declinación', 2, 4, 18),
('Introducción a la flexión verbal', 2, 5, 18),

('Segunda declinación y presente de indicativo', 3, 6, 18),
('Historia de Roma y sus personajes', 3, 7, 18),

/* ECONOMÍA */
('Ideas económicas básicas', 1, 1, 19),
('Economía y empresa', 1, 2, 19),

('Economía e ingresos y gastos del estado', 2, 3, 19),
('Economía y tipos de interés, inflación y desempleo', 2, 4, 19),

('Economía internacional', 3, 5, 19),
('Economía personal', 3, 6, 19),

/* EDUCACIÓN PARA LA CIUDADANÍA */
('La persona y su entorno', 1, 1, 21),
('Barrios, pueblos y ciudades', 1, 2, 21),

('Sociedades democráticas', 2, 3, 21),
('Los derechos humanos', 2, 4, 21),

('Un mundo globalizado, un mundo dividido', 3, 5, 21),
('Hacia un mundo mejor', 3, 6, 21);


INSERT INTO ENTRE (NOMBRE_ENTRE, DESCR_ENTRE, ID_TEMAS) VALUES
('Título de test de entrenamiento 1 Lengua Tema1', 'Descripción de test de entrenamiento', 1),
('Título de test de entrenamiento 2 Lengua Tema1', 'Descripción de test de entrenamiento', 1),
('Título de test de entrenamiento 3 Lengua Tema1', 'Descripción de test de entrenamiento', 1),
('Título de test de entrenamiento 2', 'Descripción de test de entrenamiento 2', 2);

INSERT INTO PREGU_ENTRE (ENUNCIADO_PREGU_ENTRE, ID_ENTRE) VALUES
('Las palabras que se utilizan para sustituir a un sustantivo reciben el nombre de:', 1),
('Para elaborar un trabajo, ¿qué paso se tendría que hacer en primer lugar?', 1),
('El título en una noticia debe ser:', 1),
('A las palabras que entran a formar parte de nuestro vocabulario se les denomina:', 1),
('¿Cuál de las siguientes figuras literarias aparece, de forma más frecuente, en las descripciones?', 1),
('¿Cuál de las siguientes obras es la más traducida a otras lenguas?', 1),
('Son herramientas de búsqueda de la información:', 1),
('¿Qué nombre reciben las palabras que expresan una acción?', 1),
('¿Cuál de las siguientes palabras funciona como núcleo del sintagma nominal de la oración: «María estudia todas las tardes en su casa»?', 1),
('¿Qué son los cultismos?', 1),

('La Pincoya, el Trauco y el Caleuche son:', 2),
('¿Cuál es el tipo de narrador que todo lo sabe?', 2),
('El «Cantar del Mío Cid» es:', 2),
('Período de la historia muy religioso:', 2),
('Texto literario de gran extensión:', 2),
('Voz que cuenta la historia:', 2),
('La «Ilíada» es la cólera de...', 2),
('¿Cuál es el primer libro de la lengua española?', 2),
('¿Cuál es la parte de la narración donde se presenta a los personajes?', 2),
('¿Cómo se llama el tipo de narración que deja una enseñanza moral?', 2),

('¿Qué son el coloquio, el debate, las conferencias y los discursos?', 3),
('El número en una forma verbal puede ser...', 3),
('¿Qué nos indica ".es" en una dirección de internet?', 3),
('¿Quiénes fueron los primeros pobladores de la península ibérica?', 3),
('¿En qué consiste la derivación?', 3),
('¿Cuál de las siguientes conjunciones es causal?', 3),
('En cuanto al número, ¿cómo se forma el plural de los adjetivos?', 3),
('¿Qué tres modos presenta un verbo?', 3),
('¿Cómo se denomina el diálogo oral planificado mediante el cual se obtiene información sobre la vida de una persona a través de una serie de preguntas?', 3),
('¿Quién fue el autor de «La isla del tesoso»?', 3),

('¿En qué consiste la composición?', 4),
('¿Qué clases de oraciones son las que expresan un deseo y, normalmente, van introducidas por «ojalá», «así que», etc.?', 4),
('¿Cuál de las siguientes palabras es un vulgarismo?', 4),
('¿Qué nombre reciben las narraciones breves y anónimas que, tradicionalmente, se han transmitido de forma oral?', 4),
('¿Qué es la exposición oral?', 4),
('¿Qué dos formas existen de crear nuevas palabras a partir de otras?', 4),
('¿Cómo se llamaba a las personas que recitaban y cantaban poemas relatando hazañas de héroes legendarios?', 4),
('¿Cuál de las siguientes formas verbales es una forma personal?', 4),
('¿Cuál de las siguientes palabras se debe escribir con "x"?', 4),
('Las palabras que se refieren a las personas que intervienen en la comunicación reciben el nombre de:', 4)
;

INSERT INTO RESPU_ENTRE (TEXTO_RESPU_ENTRE, PESO_RESPU_ENTRE, CORRECTA_RESPUE_ENTRE, ID_PREGU_ENTRE) VALUES
('Oración', 1, 0, 1),
('Complemento directo', 2, 0, 1),
('Pronombre', 4, 1, 1),
('Complemento del nombre', 3, 0, 1),
('Analizar la información', 3, 0, 2),
('Redactar la información', 1, 0, 2),
('Buscar la información', 2, 0, 2),
('Seleccionar el tema', 4, 1, 2),
('Breve y artificioso', 1, 0, 3),
('Breve y complejo', 3, 0, 3),
('Breve y expresivo', 4, 1, 3),
('Breve y sencillo', 2, 0, 3),
('Vocabulario', 3, 0, 4),
('Tecnicismos', 2, 0, 4),
('Préstamos lingüísticos', 4, 1, 4),
('Técnicas lingüísticas', 1, 0, 4),
('Anáfora', 1, 0, 5),
('Hipérbaton', 3, 0, 5),
('Metáfora', 4, 1, 5),
('Aliteración', 2, 0, 5),
('Don Juan Tenorio', 3, 0, 6),
('Hamlet', 2, 0, 6),
('Don Quijote de la Mancha', 4, 1, 6),
('La Celestina', 1, 0, 6),
('Internet', 3, 0, 7),
('Diccionario', 2, 0, 7),
('Enciclopedia', 1, 0, 7),
('Todas son correctas', 4, 1, 7),
('Adjetivos', 2, 0, 8),
('Verbos', 4, 1, 8),
('Adverbios', 3, 0, 8),
('Sustantivos', 1, 0, 8),
('Todas las tardes', 2, 0, 9),
('Estudia', 3, 0, 9),
('En su casa', 1, 0, 9),
('María', 4, 1, 9),
('Las palabras que provienen del latín o del griego', 4, 1, 10),
('Las palabras que provienen del hebreo', 1, 0, 10),
('Las palabras que provienen del inglés', 2, 0, 10),
('Las palabras que provienen del francés', 3, 0, 10),

('Leyenda', 4, 1, 11),
('Mito', 3, 0, 11),
('Cuento', 2, 0, 11),
('Fábula', 1, 0, 11),
('Testigo', 2, 0, 12),
('Omnisciente', 4, 1, 12),
('Observador', 3, 0, 12),
('Protagonista', 1, 0, 12),
('Mito', 1, 0, 13),
('Leyenda', 2, 0, 13),
('Cantar de gesta', 4, 1, 13),
('Epopeya', 3, 0, 13),
('Edad Media', 4, 1, 14),
('Edad Contemporánea', 2, 0, 14),
('Edad Moderna', 3, 0, 14),
('Edad Antigua', 1, 0, 14),
('Mito', 3, 0, 15),
('Novela', 4, 1, 15),
('Leyenda', 2, 0, 15),
('Cuento', 1, 0, 15),
('Narrador', 4, 1, 16),
('Personajes', 2, 0, 16),
('Autor', 3, 0, 16),
('Editor', 1, 0, 16),
('Orfeo', 2, 0, 17),
('Prometeo', 1, 0, 17),
('Aquiles', 4, 1, 17),
('Zeus', 3, 0, 17),
('La Ilíada', 2, 0, 18),
('La Odisea', 3, 0, 18),
('El Mío Cid', 4, 1, 18),
('Orfeo', 1, 0, 18),
('Inicio', 4, 1, 19),
('Nudo', 2, 0, 19),
('Desenlace', 1, 0, 19),
('Presentación', 3, 0, 19),
('Mito', 1, 0, 20),
('Leyenda', 3, 0, 20),
('Fábula', 4, 1, 20),
('Cuento', 2, 0, 20),

('Técnicas de expresión oral planificadas', 4, 1, 21),
('Técnicas de expresión oral espontáneas', 1, 0, 21),
('Técnicas de expresión oral simples', 2, 0, 21),
('Técnicas de expresión oral estructuradas', 3, 0, 21),
('Plural', 3, 0, 22),
('Plural y singular', 4, 1, 22),
('Singular', 2, 0, 22),
('Ninguna es correcta', 1, 0, 22),
('Indica cuál es el enlace de la página web', 3, 0, 23),
('Indica el tipo de buscador', 1, 0, 23),
('Indica el país que ofece la información', 4, 1, 23),
('Indica el nombre de la página web', 2, 0, 23),
('Íberos, celtas y gallegos', 2, 0, 24),
('Celtas, gallegos y vascones', 1, 0, 24),
('Vascones, íberos y gallegos', 3, 0, 24),
('Vascones, celtas e íberos', 4, 1, 24),
('Añadir un prefijo al lexema', 3, 0, 25),
('Añadir un lexema a otro lexema', 1, 0, 25),
('Añadir un sufijo al lexema', 2, 0, 25),
('Añadir un prefijo o un sufijo al lexema', 4, 1, 25),
('O sea', 2, 0, 26),
('Por tanto', 3, 0, 26),
('Sin embargo', 1, 0, 26),
('Porque', 4, 1, 26),
('Añadiendo "-es" cuando los adjetivos terminan en consonante o vocal acentuada', 4, 1, 27),
('Añadiendo "-es" cuando los adjetivos terminan en consonante', 3, 0, 27),
('Añadiendo "-s" cuando los adjetivos terminan en consonante', 2, 0, 27),
('Ninguna es correcta', 1, 0, 27),
('Acabado, inacabado e irregular', 1, 0, 28),
('Indicativo, subjuntuvo y regular', 4, 1, 28),
('Perfecto, imperfecto y regular', 3, 0, 28),
('Presente, pasado y futuro', 2, 0, 28),
('Declaración', 2, 0, 29),
('Entrevista', 4, 1, 29),
('Aclaración', 1, 0, 29),
('Biografía', 3, 0, 29),
('Gabriel García Márquez', 3, 0, 30),
('Pedro Muñoz Seca', 1, 0, 30),
('Seve Calleja', 2, 0, 30),
('Robert Louis Stevenson', 4, 1, 30),

('En unir dos morfemas ya existentes para crear una palabra', 3, 0, 31),
('En unir dos lexemas ya existentes para crear una palabra nueva', 4, 1, 31),
('En separar dos morfemas ya existentes para crear dos palabras con un significado distinto', 1, 0, 31),
('En separar dos lexemas ya existentes para crear dos palabras con un significado distinto', 2, 0, 31),
('Exclamativas', 1, 0, 32),
('Enunciativas', 3, 0, 32),
('Desiderativas', 4, 1, 32),
('Dubitativas', 2, 0, 32),
('Ejército', 1, 0, 33),
('Soldado', 2, 0, 33),
('Morir', 3, 0, 33),
('Veintiuno', 4, 1, 33),
('Cuentos reales', 1, 0, 34),
('Cuentos populares', 2, 0, 34),
('Cuentos literarios', 3, 0, 34),
('Cuentos fantásticos', 4, 1, 34),
('Está basada en la lectura, el estudio, las charlas', 2, 0, 35),
('Es la presentación oral del contenido de un tema', 4, 1, 35),
('Es una técnica de dicción y conocimiento', 3, 0, 35),
('Está basada, solamente, en las charlas', 1, 0, 35),
('Creación y formación', 1, 0, 36),
('Creación y derivación', 2, 0, 36),
('Composición y derivación', 4, 1, 36),
('Composición y creación', 3, 0, 36),
('Cantares de gesta', 2, 0, 37),
('Heroicos', 1, 0, 37),
('Romanceros', 3, 0, 37),
('Juglares', 4, 1, 37),
('Jugar', 2, 0, 38),
('Saltando', 3, 0, 38),
('Premiar', 1, 0, 38),
('Ganaría', 4, 1, 38),
('Esplanada', 4, 1, 39),
('Especial', 1, 0, 39),
('Espectáculo', 3, 0, 39),
('Estómago', 2, 1, 39),
('Pronombres demostrativos', 2, 0, 40),
('Pronombres personales', 4, 1, 40),
('Pronombres relativos', 1, 0, 40),
('Pronombres posesivos', 3, 0, 40)
;

INSERT INTO FINAL (NOMBRE_FINAL, DESCR_FINAL, ID_TEMAS) VALUES
('El lenguaje literario', 'El lenguaje literario es un lenguaje modificado, un «lenguaje figurado» por una serie de recursos expresivos o estilísticos que llaman la atención sobre la forma del mensaje.', 1),
('Título de test de final Inglés1', 'Descripción de test de final Inglés1', 148),
('La narración', 'La narración es la manera de contar una serie de acciones realizadas por unos personajes en un lugar determinado a lo largo de un tiempo. ', 2),
('Título de test de final Inglés2', 'Descripción de test de final 4', 149),
('Género nominal', 'Descripción de test de Lengua3', 3),
('Descripción. Adjetivos: forma y uso', 'Los adjetivos expresan propiedades atribuidas a los sustantivos, especificándolas o resaltándolas.', 4),
('Textos expositivos', 'Un texto expositivo es una clase de modalidad textual que presenta como un intercambio objetivo los hechos, las ideas o los conceptos.', 5),
('La narración', 'La narración consiste en contar una secuencia o una serie de acciones realizadas por unos personajes en un lugar determinado a lo largo de un tiempo, es decir, se refiere lingüística o visualmente a una sucesión de hechos.', 6),
('Los sustantivos', 'Los sustantivos son palabras cuyos referentes son clases de entidades fijas, no estados de hechos o relaciones gramaticales.', 7),
('Los adjetivos', 'El adjetivo es una clase de palabra que complementa un sustantivo para calificarlo. Expresa características o propiedades atribuidas a un sustantivo, ya sean concretas o abstractas.', 8),
('Los verbos', 'El verbo es la parte de la oración o categoría léxica que expresa acción, movimiento, existencia, consecución, condición o estado del sujeto. Sintácticamente representa una predicación.', 9),
('Cuento, novela y resumen', 'Los géneros literarios son los distintos grupos o categorías en que podemos clasificar las obras literarias atendiendo a su contenido.', 10),
('El determinante', 'Un determinante es una palabra que acompaña al sustantivo y limita o concreta su referencia.', 11),
('Título de test de final Lengua12', 'Descripción de test de Lengua12', 12),
('Título de test de final Lengua13', 'Descripción de test de Lengua13', 13),
('Título de test de final Lengua14', 'Descripción de test de Lengua14', 14),
('Título de test de final Lengua15', 'Descripción de test de Lengua15', 15),
('Título de test de final Lengua16', 'Descripción de test de Lengua16', 16),
('Título de test de final Lengua17', 'Descripción de test de Lengua17', 17),
('Título de test de final Lengua18', 'Descripción de test de Lengua18', 18),
('Título de test de final Lengua19', 'Descripción de test de Lengua19', 19),
('Título de test de final Lengua20', 'Descripción de test de Lengua20', 20),
('Título de test de final Inglés3', 'Descripción de test de final Inglés3', 150),
('Título de test de final Inglés4', 'Descripción de test de final Inglés4', 151),
('Título de test de final Inglés5', 'Descripción de test de final Inglés5', 152),
('Título de test de final Inglés6', 'Descripción de test de final Inglés6', 153),
('Título de test de final Inglés7', 'Descripción de test de final Inglés7', 154),
('Título de test de final Inglés8', 'Descripción de test de final Inglés8', 155),
('Título de test de final Inglés9', 'Descripción de test de final Inglés9', 156),
('Título de test de final Inglés10', 'Descripción de test de final Inglés10', 157),
('Título de test de final Inglés11', 'Descripción de test de final Inglés11', 158),
('Título de test de final Inglés12', 'Descripción de test de final Inglés12', 159),
('Título de test de final Inglés13', 'Descripción de test de final Inglés13', 160),
('Título de test de final Inglés14', 'Descripción de test de final Inglés14', 161),
('Título de test de final Inglés15', 'Descripción de test de final Inglés15', 162),
('Título de test de final Inglés16', 'Descripción de test de final Inglés16', 163),
('Título de test de final Inglés17', 'Descripción de test de final Inglés17', 164),
('Título de test de final Inglés18', 'Descripción de test de final Inglés18', 165),
('Título de test de final Inglés19', 'Descripción de test de final Inglés19', 166),
('Título de test de final Inglés20', 'Descripción de test de final Inglés20', 167),
('Título de test de final Inglés21', 'Descripción de test de final Inglés21', 168),
('Título de test de final Inglés22', 'Descripción de test de final Inglés22', 169);

INSERT INTO PREGU_FINAL (ENUNCIADO_PREGU_FINAL, ID_FINAL) VALUES
('¿En qué consiste la composición?', 1),
('¿Qué clases de oraciones son las que expresan un deseo y, normalmente, van introducidas por «ojalá», «así que», etc.?', 1),
('¿Cuál de las siguientes palabras es un vulgarismo?', 1),
('¿Qué nombre reciben las narraciones breves y anónimas que, tradicionalmente, se han transmitido de forma oral?', 1),
('¿Qué es la exposición oral?', 1),
('¿Qué dos formas existen de crear nuevas palabras a partir de otras?', 1),
('¿Cómo se llamaba a las personas que recitaban y cantaban poemas relatando hazañas de héroes legendarios?', 1),
('¿Cuál de las siguientes formas verbales es una forma personal?', 1),
('¿Cuál de las siguientes palabras se debe escribir con "x"?', 1),
('Las palabras que se refieren a las personas que intervienen en la comunicación reciben el nombre de:', 1),

('FINAL2 ¿Qué escritor no pertenece a la Generación del 27?', 2),
('FINAL2 ¿Qué es la Generación del 27?', 2),
('FINAL2 ¿Quién escribió «La Colmena»?', 2),
('FINAL2 ¿Qué escritora no es española?', 2),
('FINAL2 ¿Qué libro no es del siglo XX?', 2),
('FINAL2 ¿Cuál de estos libros no escribió Benito Pérez Galdós?', 2),
('FINAL2 ¿Qué poema escribió Federico García Lorca?', 2),
('FINAL2 ¿Qué escritora es la máxima representante del nturalismo en España?', 2),
('FINAL2 ¿Cómo se llamaba la compañía teatral de Federico García Lorca?', 2),
('FINAL2 ¿Quién escribió «Nada»?', 2),

('La Pincoya, el Trauco y el Caleuche son:', 3),
('¿Cuál es el tipo de narrador que todo lo sabe?', 3),
('El «Cantar del Mío Cid» es:', 3),
('Período de la historia muy religioso:', 3),
('Texto literario de gran extensión:', 3),
('Voz que cuenta la historia:', 3),
('La «Ilíada» es la cólera de...', 3),
('¿Cuál es el primer libro de la lengua española?', 3),
('¿Cuál es la parte de la narración donde se presenta a los personajes?', 3),
('¿Cómo se llama el tipo de narración que deja una enseñanza moral?', 3),

('FINAL4 ¿Qué escritor no pertenece a la Generación del 27?', 4),
('FINAL4 ¿Qué es la Generación del 27?', 4),
('FINAL4 ¿Quién escribió «La Colmena»?', 4),
('FINAL4 ¿Qué escritora no es española?', 4),
('FINAL4 ¿Qué libro no es del siglo XX?', 4),
('FINAL4 ¿Cuál de estos libros no escribió Benito Pérez Galdós?', 4),
('FINAL4 ¿Qué poema escribió Federico García Lorca?', 4),
('FINAL4 ¿Qué escritora es la máxima representante del nturalismo en España?', 4),
('FINAL4 ¿Cómo se llamaba la compañía teatral de Federico García Lorca?', 4),
('FINAL4 ¿Quién escribió «Nada»?', 4),

('¿Qué son el coloquio, el debate, las conferencias y los discursos?', 5),
('El número en una forma verbal puede ser...', 5),
('¿Qué nos indica ".es" en una dirección de internet?', 5),
('¿Quiénes fueron los primeros pobladores de la península ibérica?', 5),
('¿En qué consiste la derivación?', 5),
('¿Cuál de las siguientes conjunciones es causal?', 5),
('En cuanto al número, ¿cómo se forma el plural de los adjetivos?', 5),
('¿Qué tres modos presenta un verbo?', 5),
('¿Cómo se denomina el diálogo oral planificado mediante el cual se obtiene información sobre la vida de una persona a través de una serie de preguntas?', 5),
('¿Quién fue el autor de «La isla del tesoso»?', 5),

('¿Qué grados presentan los adjetivos calificativos?', 6),
('¿Cuál de los siguientes dramaturgos en lengua castellana pertenece al siglo XX?', 6),
('¿Cuál de los siguientes adverbios indica las circunstancias en que se desarrolla una acción?', 6),
('¿Cómo se llamaba a las personas que recitaban y cantaban poemas relatando hazañas de héroes legendarios?', 6),
('El prefijo es un tipo de morfema que:', 6),
('¿Qué tres funciones del lenguaje son las más importantes?', 6),
('¿Cómo se concreta el lenguaje humano?', 6),
('¿Cuál de las siguientes palabras está escrita incorrectamente?', 6),
('¿Cuál de las siguientes es una palabra compuesta?', 6),
('¿Cuál de las siguientes palabras está escrita incorrectamente?', 6),

('Las palabras que se utilizan para sustituir a un sustantivo reciben el nombre de:', 7),
('Para elaborar un trabajo, ¿qué paso se tendría que hacer en primer lugar?', 7),
('El título en una noticia debe ser:', 7),
('A las palabras que entran a formar parte de nuestro vocabulario se les denomina:', 7),
('¿Cuál de las siguientes figuras literarias aparece, de forma más frecuente, en las descripciones?', 7),
('¿Cuál de las siguientes obras es la más traducida a otras lenguas?', 7),
('Son herramientas de búsqueda de la información:', 7),
('¿Qué nombre reciben las palabras que expresan una acción?', 7),
('¿Cuál de las siguientes palabras funciona como núcleo del sintagma nominal de la oración: «María estudia todas las tardes en su casa»?', 7),
('¿Qué son los cultismos?', 7),

('¿Cómo se denomina a las palabras que proceden del alemán?', 8),
('En la literatura en valenciano, al siglo XVI se le denomina...', 8),
('¿Cuál de las siguientes palabras se escribe con mayúscula?', 8),
('Una metáfora en la que no aparece el término real se llama:', 8),
('¿Qué son las conjugaciones?', 8),
('¿Qué nombre recibe el grupo de palabras que se organiza en torno a un núcleo?', 8),
('Los romances que fueron recogidos por escrito en recopilaciones se denominan:', 8),
('Para acercar la acción del relato al lector se utilizará:', 8),
('¿Qué parte de la siguiente oración funciona como complemento circunstancial de lugar: «María estudia toda la tarde en su casa»?', 8),
('El valenciano es lengua oficial de...', 8),

('¿Qué son el coloquio, el debate, las conferencias y los discursos?', 9),
('El número en una forma verbal puede ser...', 9),
('¿Qué nos indica ".es" en una dirección de internet?', 9),
('¿Quiénes fueron los primeros pobladores de la península ibérica?', 9),
('¿En qué consiste la derivación?', 9),
('¿Cuál de las siguientes conjunciones es causal?', 9),
('En cuanto al número, ¿cómo se forma el plural de los adjetivos?', 9),
('¿Qué tres modos presenta un verbo?', 9),
('¿Cómo se denomina el diálogo oral planificado mediante el cual se obtiene información sobre la vida de una persona a través de una serie de preguntas?', 9),
('¿Quién fue el autor de «La isla del tesoso»?', 9),

('¿Qué grados presentan los adjetivos calificativos?', 10),
('¿Cuál de los siguientes dramaturgos en lengua castellana pertenece al siglo XX?', 10),
('¿Cuál de los siguientes adverbios indica las circunstancias en que se desarrolla una acción?', 10),
('¿Cómo se llamaba a las personas que recitaban y cantaban poemas relatando hazañas de héroes legendarios?', 10),
('El prefijo es un tipo de morfema que:', 10),
('¿Qué tres funciones del lenguaje son las más importantes?', 10),
('¿Cómo se concreta el lenguaje humano?', 10),
('¿Cuál de las siguientes palabras está escrita incorrectamente?', 10),
('¿Cuál de las siguientes es una palabra compuesta?', 10),
('¿Cuál de las siguientes palabras está escrita incorrectamente?', 10),

('¿Cómo se denomina a las palabras que proceden del alemán?', 11),
('En la literatura en valenciano, al siglo XVI se le denomina...', 11),
('¿Cuál de las siguientes palabras se escribe con mayúscula?', 11),
('Una metáfora en la que no aparece el término real se llama:', 11),
('¿Qué son las conjugaciones?', 11),
('¿Qué nombre recibe el grupo de palabras que se organiza en torno a un núcleo?', 11),
('Los romances que fueron recogidos por escrito en recopilaciones se denominan:', 11),
('Para acercar la acción del relato al lector se utilizará:', 11),
('¿Qué parte de la siguiente oración funciona como complemento circunstancial de lugar: «María estudia toda la tarde en su casa»?', 11),
('El valenciano es lengua oficial de...', 11),

('¿Cómo se denomina a las palabras que proceden del alemán?', 12),
('En la literatura en valenciano, al siglo XVI se le denomina...', 12),
('¿Cuál de las siguientes palabras se escribe con mayúscula?', 12),
('Una metáfora en la que no aparece el término real se llama:', 12),
('¿Qué son las conjugaciones?', 12),
('¿Qué nombre recibe el grupo de palabras que se organiza en torno a un núcleo?', 12),
('Los romances que fueron recogidos por escrito en recopilaciones se denominan:', 12),
('Para acercar la acción del relato al lector se utilizará:', 12),
('¿Qué parte de la siguiente oración funciona como complemento circunstancial de lugar: «María estudia toda la tarde en su casa»?', 12),
('El valenciano es lengua oficial de...', 12),

('Los adjetivos determinantes pueden ir:', 13),
('', 13),
('', 13),
('', 13),
('', 13),
('', 13),
('', 13),
('', 13),
('', 13),
('', 13)
;

INSERT INTO RESPU_FINAL (TEXTO_RESPU_FINAL, PESO_RESPU_FINAL, CORRECTA_RESPUE_FINAL, ID_PREGU_FINAL) VALUES
('En unir dos morfemas ya existentes para crear una palabra', 3, 0, 1),
('En unir dos lexemas ya existentes para crear una palabra nueva', 4, 1, 1),
('En separar dos morfemas ya existentes para crear dos palabras con un significado distinto', 1, 0, 1),
('En separar dos lexemas ya existentes para crear dos palabras con un significado distinto', 2, 0, 1),
('Exclamativas', 1, 0, 2),
('Enunciativas', 3, 0, 2),
('Desiderativas', 4, 1, 2),
('Dubitativas', 2, 0, 2),
('Ejército', 1, 0, 3),
('Soldado', 2, 0, 3),
('Morir', 3, 0, 3),
('Veintiuno', 4, 1, 3),
('Cuentos reales', 1, 0, 4),
('Cuentos populares', 2, 0, 4),
('Cuentos literarios', 3, 0, 4),
('Cuentos fantásticos', 4, 1, 4),
('Está basada en la lectura, el estudio, las charlas', 2, 0, 5),
('Es la presentación oral del contenido de un tema', 4, 1, 5),
('Es una técnica de dicción y conocimiento', 3, 0, 5),
('Está basada, solamente, en las charlas', 1, 0, 5),
('Creación y formación', 1, 0, 6),
('Creación y derivación', 2, 0, 6),
('Composición y derivación', 4, 1, 6),
('Composición y creación', 3, 0, 6),
('Cantares de gesta', 2, 0, 7),
('Heroicos', 1, 0, 7),
('Romanceros', 3, 0, 7),
('Juglares', 4, 1, 7),
('Jugar', 2, 0, 8),
('Saltando', 3, 0, 8),
('Premiar', 1, 0, 8),
('Ganaría', 4, 1, 8),
('Esplanada', 4, 1, 9),
('Especial', 1, 0, 9),
('Espectáculo', 3, 0, 9),
('Estómago', 2, 0, 9),
('Pronombres demostrativos', 2, 0, 10),
('Pronombres personales', 4, 1, 10),
('Pronombres relativos', 1, 0, 10),
('Pronombres posesivos', 3, 0, 10),

('Respuesta 1', 1, 0, 11),
('Respuesta 2', 2, 0, 11),
('Respuesta 3', 3, 0, 11),
('Respuesta 4', 4, 1, 11),
('Respuesta 1', 1, 0, 12),
('Respuesta 2', 2, 0, 12),
('Respuesta 3', 3, 0, 12),
('Respuesta 4', 4, 1, 12),
('Respuesta 1', 1, 0, 13),
('Respuesta 2', 2, 0, 13),
('Respuesta 3', 3, 0, 13),
('Respuesta 4', 4, 1, 13),
('Respuesta 1', 1, 0, 14),
('Respuesta 2', 2, 0, 14),
('Respuesta 3', 3, 0, 14),
('Respuesta 4', 4, 1, 14),
('Respuesta 1', 1, 0, 15),
('Respuesta 2', 2, 0, 15),
('Respuesta 3', 3, 0, 15),
('Respuesta 4', 4, 1, 15),
('Respuesta 1', 1, 0, 16),
('Respuesta 2', 2, 0, 16),
('Respuesta 3', 3, 0, 16),
('Respuesta 4', 4, 1, 16),
('Respuesta 1', 1, 0, 17),
('Respuesta 2', 2, 0, 17),
('Respuesta 3', 3, 0, 17),
('Respuesta 4', 4, 1, 17),
('Respuesta 1', 1, 0, 18),
('Respuesta 2', 2, 0, 18),
('Respuesta 3', 3, 0, 18),
('Respuesta 4', 4, 1, 18),
('Respuesta 1', 1, 0, 19),
('Respuesta 2', 2, 0, 19),
('Respuesta 3', 3, 0, 19),
('Respuesta 4', 4, 1, 19),
('Respuesta 1', 1, 0, 20),
('Respuesta 2', 2, 0, 20),
('Respuesta 3', 3, 0, 20),
('Respuesta 4', 4, 1, 20),

('Leyenda', 4, 1, 21),
('Mito', 3, 0, 21),
('Cuento', 2, 0, 21),
('Fábula', 1, 0, 21),
('Testigo', 2, 0, 22),
('Omnisciente', 4, 1, 22),
('Observador', 3, 0, 22),
('Protagonista', 1, 0, 22),
('Mito', 1, 0, 23),
('Leyenda', 2, 0, 23),
('Cantar de gesta', 4, 1, 23),
('Epopeya', 3, 0, 23),
('Edad Media', 4, 1, 24),
('Edad Contemporánea', 2, 0, 24),
('Edad Moderna', 3, 0, 24),
('Edad Antigua', 1, 0, 24),
('Mito', 3, 0, 25),
('Novela', 4, 1, 25),
('Leyenda', 2, 0, 25),
('Cuento', 1, 0, 25),
('Narrador', 4, 1, 26),
('Personajes', 2, 0, 26),
('Autor', 3, 0, 26),
('Editor', 1, 0, 26),
('Orfeo', 2, 0, 27),
('Prometeo', 1, 0, 27),
('Aquiles', 4, 1, 27),
('Zeus', 3, 0, 27),
('La Ilíada', 2, 0, 28),
('La Odisea', 3, 0, 28),
('El Mío Cid', 4, 1, 28),
('Orfeo', 1, 0, 28),
('Inicio', 4, 1, 29),
('Nudo', 2, 0, 29),
('Desenlace', 1, 0, 29),
('Presentación', 3, 0, 29),
('Mito', 1, 0, 30),
('Leyenda', 3, 0, 30),
('Fábula', 4, 1, 30),
('Cuento', 2, 0, 30),

('Respuesta 1', 1, 0, 31),
('Respuesta 2', 2, 0, 31),
('Respuesta 3', 3, 0, 31),
('Respuesta 4', 4, 1, 31),
('Respuesta 1', 1, 0, 32),
('Respuesta 2', 2, 0, 32),
('Respuesta 3', 3, 0, 32),
('Respuesta 4', 4, 1, 32),
('Respuesta 1', 1, 0, 33),
('Respuesta 2', 2, 0, 33),
('Respuesta 3', 3, 0, 33),
('Respuesta 4', 4, 1, 33),
('Respuesta 1', 1, 0, 34),
('Respuesta 2', 2, 0, 34),
('Respuesta 3', 3, 0, 34),
('Respuesta 4', 4, 1, 34),
('Respuesta 1', 1, 0, 35),
('Respuesta 2', 2, 0, 35),
('Respuesta 3', 3, 0, 35),
('Respuesta 4', 4, 1, 35),
('Respuesta 1', 1, 0, 36),
('Respuesta 2', 2, 0, 36),
('Respuesta 3', 3, 0, 36),
('Respuesta 4', 4, 1, 36),
('Respuesta 1', 1, 0, 37),
('Respuesta 2', 2, 0, 37),
('Respuesta 3', 3, 0, 37),
('Respuesta 4', 4, 1, 37),
('Respuesta 1', 1, 0, 38),
('Respuesta 2', 2, 0, 38),
('Respuesta 3', 3, 0, 38),
('Respuesta 4', 4, 1, 38),
('Respuesta 1', 1, 0, 39),
('Respuesta 2', 2, 0, 39),
('Respuesta 3', 3, 0, 39),
('Respuesta 4', 4, 1, 39),
('Respuesta 1', 1, 0, 40),
('Respuesta 2', 2, 0, 40),
('Respuesta 3', 3, 0, 40),
('Respuesta 4', 4, 1, 40),

('Técnicas de expresión oral planificadas', 4, 1, 41),
('Técnicas de expresión oral espontáneas', 1, 0, 41),
('Técnicas de expresión oral simples', 2, 0, 41),
('Técnicas de expresión oral estructuradas', 3, 0, 41),
('Plural', 3, 0, 42),
('Plural y singular', 4, 1, 42),
('Singular', 2, 0, 42),
('Ninguna es correcta', 1, 0, 42),
('Indica cuál es el enlace de la página web', 3, 0, 43),
('Indica el tipo de buscador', 1, 0, 43),
('Indica el país que ofece la información', 4, 1, 43),
('Indica el nombre de la página web', 2, 0, 43),
('Íberos, celtas y gallegos', 2, 0, 44),
('Celtas, gallegos y vascones', 1, 0, 44),
('Vascones, íberos y gallegos', 3, 0, 44),
('Vascones, celtas e íberos', 4, 1, 44),
('Añadir un prefijo al lexema', 3, 0, 45),
('Añadir un lexema a otro lexema', 1, 0, 45),
('Añadir un sufijo al lexema', 2, 0, 45),
('Añadir un prefijo o un sufijo al lexema', 4, 1, 45),
('O sea', 2, 0, 46),
('Por tanto', 3, 0, 46),
('Sin embargo', 1, 0, 46),
('Porque', 4, 1, 46),
('Añadiendo "-es" cuando los adjetivos terminan en consonante o vocal acentuada', 4, 1, 47),
('Añadiendo "-es" cuando los adjetivos terminan en consonante', 3, 0, 47),
('Añadiendo "-s" cuando los adjetivos terminan en consonante', 2, 0, 47),
('Ninguna es correcta', 1, 0, 47),
('Acabado, inacabado e irregular', 1, 0, 48),
('Indicativo, subjuntuvo y regular', 4, 1, 48),
('Perfecto, imperfecto y regular', 3, 0, 48),
('Presente, pasado y futuro', 2, 0, 48),
('Declaración', 2, 0, 49),
('Entrevista', 4, 1, 49),
('Aclaración', 1, 0, 49),
('Biografía', 3, 0, 49),
('Gabriel García Márquez', 3, 0, 50),
('Pedro Muñoz Seca', 1, 0, 50),
('Seve Calleja', 2, 0, 50),
('Robert Louis Stevenson', 4, 1, 50),

('Grado negativo y comparativo', 2, 0, 51),
('Grado positivo y negativo', 1, 0, 51),
('Grado negativo, comparativo y diminutivo', 3, 0, 51),
('Grado positivo, comparativo y superlativo', 4, 1, 51),
('Lope de Vega', 2, 0, 52),
('Federico García Lorca', 4, 1, 52),
('Luis de Góngora', 1, 0, 52),
('José Zorrilla', 3, 0, 52),
('Demasiado', 1, 0, 53),
('Muy', 2, 0, 53),
('Ya', 4, 1, 53),
('Nada', 3, 0, 53),
('Heroicos', 1, 0, 54),
('Cantares de gesta', 2, 0, 54),
('Juglares', 4, 1, 54),
('Romanceros', 3, 0, 54),
('Se antepone al lexema para formar una nueva palabra', 4, 1, 55),
('Se pospone al lexema para modificar una palabra', 1, 0, 55),
('Se antepone al lexema para modificar una palabra', 3, 0, 55),
('Se pospone al lexema para formar una nueva palabra', 2, 0, 55),
('Función apelativa, representativa y expresiva', 4, 1, 56),
('Función apelativa, afirmativa y enunciativa', 1, 0, 56),
('Función apelativa, enunciativa e interrogativa', 2, 0, 56),
('Función apelativa, expresiva e interrogativa', 3, 0, 56),
('Con la lengua', 4, 1, 57),
('Con el lenguaje', 3, 0, 57),
('Con la expresión', 2, 0, 57),
('Con la literatura', 1, 0, 57),
('Incomodidad', 2, 0, 58),
('Abrelatas', 4, 1, 58),
('Insonoro', 3, 0, 58),
('Legible', 1, 0, 58),
('Expirar', 2, 0, 59),
('Estender', 4, 1, 59),
('Extraer', 3, 0, 59),
('Estío', 1, 0, 59),
('Balance', 2, 0, 60),
('Abdicar', 1, 0, 60),
('Beligerante', 3, 0, 60),
('Bicepresidente', 4, 1, 60),

('Oración', 1, 0, 61),
('Complemento directo', 2, 0, 61),
('Pronombre', 4, 1, 61),
('Complemento del nombre', 3, 0, 61),
('Analizar la información', 3, 0, 62),
('Redactar la información', 1, 0, 62),
('Buscar la información', 2, 0, 62),
('Seleccionar el tema', 4, 1, 62),
('Breve y artificioso', 1, 0, 63),
('Breve y complejo', 3, 0, 63),
('Breve y expresivo', 4, 1, 63),
('Breve y sencillo', 2, 0, 63),
('Vocabulario', 3, 0, 64),
('Tecnicismos', 2, 0, 64),
('Préstamos lingüísticos', 4, 1, 64),
('Técnicas lingüísticas', 1, 0, 64),
('Anáfora', 1, 0, 65),
('Hipérbaton', 3, 0, 65),
('Metáfora', 4, 1, 65),
('Aliteración', 2, 0, 65),
('Don Juan Tenorio', 3, 0, 66),
('Hamlet', 2, 0, 66),
('Don Quijote de la Mancha', 4, 1, 66),
('La Celestina', 1, 0, 66),
('Internet', 3, 0, 67),
('Diccionario', 2, 0, 67),
('Enciclopedia', 1, 0, 67),
('Todas son correctas', 4, 1, 67),
('Adjetivos', 2, 0, 68),
('Verbos', 4, 1, 68),
('Adverbios', 3, 0, 68),
('Sustantivos', 1, 0, 68),
('Todas las tardes', 2, 0, 69),
('Estudia', 3, 0, 69),
('En su casa', 1, 0, 69),
('María', 4, 1, 69),
('Las palabras que provienen del latín o del griego', 4, 1, 70),
('Las palabras que provienen del hebreo', 1, 0, 70),
('Las palabras que provienen del inglés', 2, 0, 70),
('Las palabras que provienen del francés', 3, 0, 70),

('Anglicismos', 3, 0, 71),
('Americanismos', 2, 0, 71),
('Galicismos', 1, 0, 71),
('Germanismos', 4, 1, 71),
('Siglo de Oro', 4, 1, 72),
('Siglo de Bronce', 1, 0, 72),
('Siglo de Plata', 2, 0, 72),
('Siglo Ilustrado', 3, 0, 72),
('Verano', 1, 0, 73),
('Abril', 2, 0, 73),
('Jueves', 3, 0, 73),
('La Giralda', 4, 1, 73),
('Metáfora impura', 1, 0, 74),
('Metáfora irreal', 2, 0, 74),
('Metáfora pura', 4, 1, 74),
('Metáfora real', 3, 0, 74),
('Lexemas', 2, 0, 75),
('Sufijos', 3, 0, 75),
('Morfemas', 4, 1, 75),
('Prefijos', 1, 0, 75),
('Sintagma', 4, 1, 76),
('Palabra', 2, 0, 76),
('Lexema', 3, 0, 76),
('Oración', 1, 0, 76),
('Cantares', 1, 0, 77),
('Romanceros', 3, 0, 77),
('Cancioneros', 2, 0, 77),
('Líricos', 4, 1, 77),
('El futuro', 2, 0, 78),
('El pasado', 3, 0, 78),
('El presente', 4, 1, 78),
('El condicional', 1, 0, 78),
('Estudia', 2, 0, 79),
('María', 1, 0, 79),
('En su casa', 4, 1, 79),
('Todas las tardes', 3, 0, 79),
('La Comunidad Valenciana', 4, 1, 80),
('Cataluña y la Comunidad Valenciana', 2, 0, 80),
('La Comunidad Valenciana y las Islas Baleares', 3, 0, 80),
('Ninguna de las anteriores es correcta', 1, 0, 80),

('Técnicas de expresión oral planificadas', 4, 1, 81),
('Técnicas de expresión oral espontáneas', 1, 0, 81),
('Técnicas de expresión oral simples', 2, 0, 81),
('Técnicas de expresión oral estructuradas', 3, 0, 81),
('Plural', 3, 0, 82),
('Plural y singular', 4, 1, 82),
('Singular', 2, 0, 82),
('Ninguna es correcta', 1, 0, 82),
('Indica cuál es el enlace de la página web', 3, 0, 83),
('Indica el tipo de buscador', 1, 0, 83),
('Indica el país que ofece la información', 4, 1, 83),
('Indica el nombre de la página web', 2, 0, 83),
('Íberos, celtas y gallegos', 2, 0, 84),
('Celtas, gallegos y vascones', 1, 0, 84),
('Vascones, íberos y gallegos', 3, 0, 84),
('Vascones, celtas e íberos', 4, 1, 84),
('Añadir un prefijo al lexema', 3, 0, 85),
('Añadir un lexema a otro lexema', 1, 0, 85),
('Añadir un sufijo al lexema', 2, 0, 85),
('Añadir un prefijo o un sufijo al lexema', 4, 1, 85),
('O sea', 2, 0, 86),
('Por tanto', 3, 0, 86),
('Sin embargo', 1, 0, 86),
('Porque', 4, 1, 86),
('Añadiendo "-es" cuando los adjetivos terminan en consonante o vocal acentuada', 4, 1, 87),
('Añadiendo "-es" cuando los adjetivos terminan en consonante', 3, 0, 87),
('Añadiendo "-s" cuando los adjetivos terminan en consonante', 2, 0, 87),
('Ninguna es correcta', 1, 0, 87),
('Acabado, inacabado e irregular', 1, 0, 88),
('Indicativo, subjuntuvo y regular', 4, 1, 88),
('Perfecto, imperfecto y regular', 3, 0, 88),
('Presente, pasado y futuro', 2, 0, 88),
('Declaración', 2, 0, 89),
('Entrevista', 4, 1, 89),
('Aclaración', 1, 0, 89),
('Biografía', 3, 0, 89),
('Gabriel García Márquez', 3, 0, 90),
('Pedro Muñoz Seca', 1, 0, 90),
('Seve Calleja', 2, 0, 90),
('Robert Louis Stevenson', 4, 1, 90),

('Grado negativo y comparativo', 2, 0, 91),
('Grado positivo y negativo', 1, 0, 91),
('Grado negativo, comparativo y diminutivo', 3, 0, 91),
('Grado positivo, comparativo y superlativo', 4, 1, 91),
('Lope de Vega', 2, 1, 92),
('Federico García Lorca', 4, 1, 92),
('Luis de Góngora', 1, 0, 92),
('José Zorrilla', 3, 0, 92),
('Demasiado', 1, 0, 93),
('Muy', 2, 0, 93),
('Ya', 4, 1, 93),
('Nada', 3, 0, 93),
('Heroicos', 1, 0, 94),
('Cantares de gesta', 2, 0, 94),
('Juglares', 4, 1, 94),
('Romanceros', 3, 0, 94),
('Se antepone al lexema para formar una nueva palabra', 4, 1, 95),
('Se pospone al lexema para modificar una palabra', 1, 0, 95),
('Se antepone al lexema para modificar una palabra', 3, 0, 95),
('Se pospone al lexema para formar una nueva palabra', 2, 0, 95),
('Función apelativa, representativa y expresiva', 4, 1, 96),
('Función apelativa, afirmativa y enunciativa', 1, 0, 96),
('Función apelativa, enunciativa e interrogativa', 2, 0, 96),
('Función apelativa, expresiva e interrogativa', 3, 0, 96),
('Con la lengua', 4, 1, 97),
('Con el lenguaje', 3, 0, 97),
('Con la expresión', 2, 0, 97),
('Con la literatura', 1, 0, 97),
('Incomodidad', 2, 0, 98),
('Abrelatas', 4, 1, 98),
('Insonoro', 3, 0, 98),
('Legible', 1, 0, 98),
('Expirar', 2, 0, 99),
('Estender', 4, 1, 99),
('Extraer', 3, 0, 99),
('Estío', 1, 0, 99),
('Balance', 2, 0, 100),
('Abdicar', 1, 0, 100),
('Beligerante', 3, 0, 100),
('Bicepresidente', 4, 1, 100),

('Anglicismos', 3, 0, 101),
('Americanismos', 2, 0, 101),
('Galicismos', 1, 0, 101),
('Germanismos', 4, 1, 101),
('Siglo de Oro', 4, 1, 102),
('Siglo de Bronce', 1, 0, 102),
('Siglo de Plata', 2, 0, 102),
('Siglo Ilustrado', 3, 0, 102),
('Verano', 1, 0, 103),
('Abril', 2, 0, 103),
('Jueves', 3, 0, 103),
('La Giralda', 4, 1, 103),
('Metáfora impura', 1, 0, 104),
('Metáfora irreal', 2, 0, 104),
('Metáfora pura', 4, 1, 104),
('Metáfora real', 3, 0, 104),
('Lexemas', 2, 0, 105),
('Sufijos', 3, 0, 105),
('Morfemas', 4, 1, 105),
('Prefijos', 1, 0, 105),
('Sintagma', 4, 1, 106),
('Palabra', 2, 0, 106),
('Lexema', 3, 0, 106),
('Oración', 1, 0, 106),
('Cantares', 1, 0, 107),
('Romanceros', 3, 0, 107),
('Cancioneros', 2, 0, 107),
('Líricos', 4, 1, 107),
('El futuro', 2, 0, 108),
('El pasado', 3, 0, 108),
('El presente', 4, 1, 108),
('El condicional', 1, 0, 108),
('Estudia', 2, 0, 109),
('María', 1, 0, 109),
('En su casa', 4, 1, 109),
('Todas las tardes', 3, 0, 109),
('La Comunidad Valenciana', 4, 1, 110),
('Cataluña y la Comunidad Valenciana', 2, 0, 110),
('La Comunidad Valenciana y las Islas Baleares', 3, 0, 110),
('Ninguna de las anteriores es correcta', 1, 0, 110),

('Anglicismos', 3, 0, 111),
('Americanismos', 2, 0, 111),
('Galicismos', 1, 0, 111),
('Germanismos', 4, 1, 111),
('Siglo de Oro', 4, 1, 112),
('Siglo de Bronce', 1, 0, 112),
('Siglo de Plata', 2, 0, 112),
('Siglo Ilustrado', 3, 0, 112),
('Verano', 1, 0, 113),
('Abril', 2, 0, 113),
('Jueves', 3, 0, 113),
('La Giralda', 4, 1, 113),
('Metáfora impura', 1, 0, 114),
('Metáfora irreal', 2, 0, 114),
('Metáfora pura', 4, 1, 114),
('Metáfora real', 3, 0, 114),
('Lexemas', 2, 0, 115),
('Sufijos', 3, 0, 115),
('Morfemas', 4, 1, 115),
('Prefijos', 1, 0, 115),
('Sintagma', 4, 1, 116),
('Palabra', 2, 0, 116),
('Lexema', 3, 0, 116),
('Oración', 1, 0, 116),
('Cantares', 1, 0, 117),
('Romanceros', 3, 0, 117),
('Cancioneros', 2, 0, 117),
('Líricos', 4, 1, 117),
('El futuro', 2, 0, 118),
('El pasado', 3, 0, 118),
('El presente', 4, 1, 118),
('El condicional', 1, 0, 118),
('Estudia', 2, 0, 119),
('María', 1, 0, 119),
('En su casa', 4, 1, 119),
('Todas las tardes', 3, 0, 119),
('La Comunidad Valenciana', 4, 1, 120),
('Cataluña y la Comunidad Valenciana', 2, 0, 120),
('La Comunidad Valenciana y las Islas Baleares', 3, 0, 120),
('Ninguna de las anteriores es correcta', 1, 0, 120)
;

INSERT INTO REL_CURSO_ASIGN (ID_CURSO, ID_ASIGN) VALUES
(1,1),
(1,2),
(1,3),
(1,4),
(1,5),
(1,6),
(1,7),
(2,1),
(2,2),
(2,3),
(2,4),
(2,5),
(2,6),
(2,7),
(2,7),
(3,1),
(3,2),
(3,3),
(3,4),
(3,5),
(3,6),
(3,7),
(4,1),
(4,2),
(4,3),
(4,4),
(4,5),
(4,6),
(4,7),
(5,2),
(5,3),
(5,4),
(5,5),
(5,6),
(5,7),
(6,1),
(6,2),
(6,3),
(6,4),
(6,5),
(6,6),
(6,7),
(7,1),
(7,2),
(7,3),
(7,4),
(7,5),
(7,6),
(7,7),
(8,1),
(8,2),
(8,3),
(8,4),
(8,5),
(8,6),
(8,7);


INSERT INTO REL_ALUMN_ENTRE (FECHA_REL_ALUMN_ENTRE, ID_ALUMN, ID_ENTRE) VALUES
(DATE('2017-11-01'), 1, 1);

INSERT INTO REL_ALUMN_FINAL (FECHA_REL_ALUMN_FINAL, PUNTOS_REL_ALUMN_FINAL, ID_ALUMN, ID_FINAL) VALUES
(DATE('2017-11-01'),30, 1, 1),
(DATE('2017-12-20'),35, 1, 2),
(DATE('2017-11-01'),15, 1, 3);

INSERT INTO RECOM (NOMBRE_RECOM, COSTE_RECOM) VALUES
("Entrada de cine", 40),
("Descuento en restaurante", 60),
("Descuento en material de papelería", 30),
("Entrada VIP en la Sala Sol", 160),
("Descuento en Asos", 120);

INSERT INTO REL_ALUMN_RECOM (ID_ALUMN, ID_RECOM) VALUES
(1,1),
(1,2),
(1,3);

UPDATE TEMAS SET ICON_TEMAS = '../img/tema01.jpg' WHERE ID_ASIGN = 1 OR ID_ASIGN = 2;
