INSERT INTO CENTR (NOMBRE_CENTR, COMUNIDAD_CENTR, MUNICIPIO_CENTR, CP_CENTR) VALUES
('I.E.S. Alameda de Osuna', 'Comunidad de Madrid', 'Madrid', 28042),
('I.E.S. Alfredo Kraus', 'Comunidad de Madrid', 'Madrid', 28022),
('I.E.S. Antonio Domínguez Ortiz', 'Comunidad de Madrid', 'Madrid', 28038),
('I.E.S. Avenida de los Toreros', 'Comunidad de Madrid', 'Madrid', 28028),
('I.E.S. Beatriz Galindo', 'Comunidad de Madrid', 'Madrid', 28001),
('I.E.S. Blas de Otero', 'Comunidad de Madrid', 'Madrid', 28024),
('I.E.S. Cardenal Herrera Oria', 'Comunidad de Madrid', 'Madrid', 28034),
('I.E.S. Cervantes', 'Comunidad de Madrid', 'Madrid', 28012),
('I.E.S. Ciudad de Jaen', 'Comunidad de Madrid', 'Madrid', 28041),
('I.E.S. Ciudad de los Poetas', 'Comunidad de Madrid', 'Madrid', 28039),
('I.E.S. Conde Orgaz', 'Comunidad de Madrid', 'Madrid', 28043),
('I.E.S. Fortuny', 'Comunidad de Madrid', 'Madrid', 28010),
('I.E.S. Francisco de Goya', 'Comunidad de Madrid', 'Madrid', 28017),
('I.E.S. Francisco de Quevedo', 'Madrid', 'Madrid', 28037),
('I.E.S. Gabriel García Márquez', 'Madrid', 'Madrid', 28033),
('I.E.S. García Morato', 'Madrid', 'Madrid', 28044),
('I.E.S. Gran Capitán', 'Madrid', 'Madrid', 28005),
('I.E.S. Gomez Moreno', 'Madrid', 'Madrid', 28037),
('I.E.S. Isaac Newton', 'Madrid', 'Madrid', 28035),
('I.E.S. Joaquín Rodrigo', 'Madrid', 'Madrid', 28032),
('I.E.S. Joaquín Turina', 'Madrid', 'Madrid', 28003),
('I.E.S. Juan de la Cierva', 'Madrid', 'Madrid', 28005),
('I.E.S. Juan de Castilla', 'Madrid', 'Madrid', 28030),
('I.E.S. La Estrella', 'Madrid', 'Madrid', 28007),
('I.E.S. Lope de Vega', 'Madrid', 'Madrid', 28015),
('I.E.S. Manuel Fraga Iribarne', 'Madrid', 'Madrid', 28050),
('I.E.S. Mariano José de Larra', 'Madrid', 'Madrid', 28047),
('I.E.S. María Rodrigo', 'Madrid', 'Madrid', 28051),
('I.E.S. Mirasierra', 'Madrid', 'Madrid', 28034),
('I.E.S. Nuestra Señora de la Almudena', 'Madrid', 'Madrid', 28039),
('I.E.S. Pedro Salines', 'Madrid', 'Madrid', 28026),
('I.E.S. Príncipe Felipe', 'Madrid', 'Madrid', 28029),
('I.E.S. Ramiro de Maeztu', 'Madrid', 'Madrid', 28006),
('I.E.S. Ramón y Cajal', 'Madrid', 'Madrid', 28050),
('I.E.S. Rey Pastor', 'Madrid', 'Madrid', 28030),
('I.E.S. San Cristobal de los Ángeles', 'Madrid', 'Madrid', 28021),
('I.E.S. San Isidro', 'Madrid', 'Madrid', 28005),
('I.E.S. San Juan Bautista', 'Madrid', 'Madrid', 28043),
('I.E.S. Santamarta', 'Madrid', 'Madrid', 28016),
('I.E.S. Tirso de Molina', 'Madrid', 'Madrid', 28038),
('I.E.S. Valdebernardo', 'Madrid', 'Madrid', 28032),
('I.E.S. Villa de Vallecas', 'Madrid', 'Madrid', 28031),
('I.E.S. Villablanca', 'Madrid', 'Madrid', 28032);


INSERT INTO CURSO (NIVEL_CURSO, ID_CENTR) VALUES
('1º E. S. O.', 1),
('2º E. S. O.', 1),
('3º E. S. O.', 1),
('4º E. S. O.', 1),
('1º E. S. O.', 2),
('2º E. S. O.', 2),
('3º E. S. O.', 2),
('4º E. S. O.', 2),
('1º E. S. O.', 3),
('2º E. S. O.', 3),
('3º E. S. O.', 3),
('4º E. S. O.', 3),
('1º E. S. O.', 4),
('2º E. S. O.', 4),
('3º E. S. O.', 4),
('4º E. S. O.', 4),
('1º E. S. O.', 5),
('2º E. S. O.', 5),
('3º E. S. O.', 5),
('4º E. S. O.', 5),
('1º E. S. O.', 6),
('2º E. S. O.', 6),
('3º E. S. O.', 6),
('4º E. S. O.', 6),
('1º E. S. O.', 7),
('2º E. S. O.', 7),
('3º E. S. O.', 7),
('4º E. S. O.', 7),
('1º E. S. O.', 8),
('2º E. S. O.', 8),
('3º E. S. O.', 8),
('4º E. S. O.', 8),
('1º E. S. O.', 9),
('2º E. S. O.', 9),
('3º E. S. O.', 9),
('4º E. S. O.', 9),
('1º E. S. O.', 10),
('2º E. S. O.', 10),
('3º E. S. O.', 10),
('4º E. S. O.', 10),
('1º E. S. O.', 11),
('2º E. S. O.', 11),
('3º E. S. O.', 11),
('4º E. S. O.', 11),
('1º E. S. O.', 12),
('2º E. S. O.', 12),
('3º E. S. O.', 12),
('4º E. S. O.', 12),
('1º E. S. O.', 13),
('2º E. S. O.', 13),
('3º E. S. O.', 13),
('4º E. S. O.', 13);


INSERT INTO GRUPO (LETRA_GRUPO, ID_CURSO) VALUES
('A', 1),
('B', 1),
('A', 2),
('B', 2),
('A', 3),
('B', 3),
('A', 4),
('B', 4),
('A', 5),
('B', 5),
('A', 6),
('B', 6),
('A', 7),
('B', 7),
('A', 8),
('B', 8),
('A', 9),
('B', 9),
('A', 10),
('B', 10),
('A', 11),
('B', 11),
('A', 12),
('B', 12),
('A', 13),
('B', 13);


INSERT INTO ALUMN (NOMBRE_ALUMN, APELLIDO_ALUMN, EMAIL_ALUMN, CONTRASENA_ALUMN, EXPERIENCIA_ALUMN, PUNTOS_ALUMN, IMG_ALUMN, ID_GRUPO) VALUES
('Lola', 'Pérez', 'lolaperez@gmail.com', 'cont5678', 4, 1200, 'web/img/alumno1.jpg', 1),
('Raúl', 'González', 'raulitog@gmail.com', 'cont5678', 6, 1520, 'web/img/alumno2.jpg', 1),
('Elena', 'Rodríguez', 'e.rodriguez@gmail.com', 'cont5678', 7, 800, 'web/img/alumno3.jpg', 1),
('María', 'Alonso', 'maria.alonso@gmail.com', 'cont5678', 3, 1654, 'web/img/alumno4.jpg', 1),
('Roberto', 'García', 'robertoG@gmail.com', 'cont5678', 8, 1935, 'web/img/alumno5.jpg', 1),

('Álvaro', 'Sánchez', 'a.sanchez1@gmail.com', 'cont5678', 8, 1735, 'web/img/alumno6.jpg', 2),
('Sofía', 'Santos', 'sofiasantos@gmail.com', 'cont5678', 6, 1408, 'web/img/alumno7.jpg', 2),
('Adrián', 'Martínez', 'a.martinez@gmail.com', 'cont5678', 4, 1735, 'web/img/alumno8.jpg', 2),
('Mario', 'Pascual', 'marioPascual@gmail.com', 'cont5678', 5, 1103, 'web/img/alumno9.jpg', 2),

('Lola', 'Pérez', 'lolaperez@gmail.com', 'cont5678', 7, 1200, 'web/img/alumno1.jpg', 3),
('Raúl', 'González', 'raulitog@gmail.com', 'cont5678', 6, 1520, 'web/img/alumno2.jpg', 3),
('Elena', 'Rodríguez', 'e.rodriguez@gmail.com', 'cont5678', 4, 800, 'web/img/alumno3.jpg', 3),
('María', 'Alonso', 'maria.alonso@gmail.com', 'cont5678', 3, 1654, 'web/img/alumno4.jpg', 3),
('Roberto', 'García', 'robertoG@gmail.com', 'cont5678', 5, 1935, 'web/img/alumno5.jpg', 3),

('Lola', 'Pérez', 'lolaperez@gmail.com', 'cont5678', 7, 1200, 'web/img/alumno1.jpg', 4),
('Raúl', 'González', 'raulitog@gmail.com', 'cont5678', 6, 1520, 'web/img/alumno2.jpg', 4),
('Elena', 'Rodríguez', 'e.rodriguez@gmail.com', 'cont5678', 4, 800, 'web/img/alumno3.jpg', 4),
('María', 'Alonso', 'maria.alonso@gmail.com', 'cont5678', 3, 1654, 'web/img/alumno4.jpg', 4),
('Roberto', 'García', 'robertoG@gmail.com', 'cont5678', 5, 1935, 'web/img/alumno5.jpg', 4),

('Lola', 'Pérez', 'lolaperez@gmail.com', 'cont5678', 7, 1200, 'web/img/alumno1.jpg', 5),
('Raúl', 'González', 'raulitog@gmail.com', 'cont5678', 6, 1520, 'web/img/alumno2.jpg', 5),
('Elena', 'Rodríguez', 'e.rodriguez@gmail.com', 'cont5678', 4, 800, 'web/img/alumno3.jpg', 5),
('María', 'Alonso', 'maria.alonso@gmail.com', 'cont5678', 3, 1654, 'web/img/alumno4.jpg', 5),
('Roberto', 'García', 'robertoG@gmail.com', 'cont5678', 5, 1935, 'web/img/alumno5.jpg', 5),

('Lola', 'Pérez', 'lolaperez@gmail.com', 'cont5678', 7, 1200, 'web/img/alumno1.jpg', 6),
('Raúl', 'González', 'raulitog@gmail.com', 'cont5678', 6, 1520, 'web/img/alumno2.jpg', 6),
('Elena', 'Rodríguez', 'e.rodriguez@gmail.com', 'cont5678', 4, 800, 'web/img/alumno3.jpg', 6),
('María', 'Alonso', 'maria.alonso@gmail.com', 'cont5678', 3, 1654, 'web/img/alumno4.jpg', 6),
('Roberto', 'García', 'robertoG@gmail.com', 'cont5678', 5, 1935, 'web/img/alumno5.jpg', 6),

('Lola', 'Pérez', 'lolaperez@gmail.com', 'cont5678', 7, 1200, 'web/img/alumno1.jpg', 7),
('Raúl', 'González', 'raulitog@gmail.com', 'cont5678', 6, 1520, 'web/img/alumno2.jpg', 7),
('Elena', 'Rodríguez', 'e.rodriguez@gmail.com', 'cont5678', 4, 800, 'web/img/alumno3.jpg', 7),
('María', 'Alonso', 'maria.alonso@gmail.com', 'cont5678', 3, 1654, 'web/img/alumno4.jpg', 7),
('Roberto', 'García', 'robertoG@gmail.com', 'cont5678', 5, 1935, 'web/img/alumno5.jpg', 7),

('Lola', 'Pérez', 'lolaperez@gmail.com', 'cont5678', 7, 1200, 'web/img/alumno1.jpg', 8),
('Raúl', 'González', 'raulitog@gmail.com', 'cont5678', 6, 1520, 'web/img/alumno2.jpg', 8),
('Elena', 'Rodríguez', 'e.rodriguez@gmail.com', 'cont5678', 4, 800, 'web/img/alumno3.jpg', 8),
('María', 'Alonso', 'maria.alonso@gmail.com', 'cont5678', 3, 1654, 'web/img/alumno4.jpg', 8),
('Roberto', 'García', 'robertoG@gmail.com', 'cont5678', 5, 1935, 'web/img/alumno5.jpg', 8),

('Lola', 'Pérez', 'lolaperez@gmail.com', 'cont5678', 7, 1200, 'web/img/alumno1.jpg', 9),
('Raúl', 'González', 'raulitog@gmail.com', 'cont5678', 6, 1520, 'web/img/alumno2.jpg', 9),
('Elena', 'Rodríguez', 'e.rodriguez@gmail.com', 'cont5678', 4, 800, 'web/img/alumno3.jpg', 9),
('María', 'Alonso', 'maria.alonso@gmail.com', 'cont5678', 3, 1654, 'web/img/alumno4.jpg', 9),
('Roberto', 'García', 'robertoG@gmail.com', 'cont5678', 5, 1935, 'web/img/alumno5.jpg', 9),

('Lola', 'Pérez', 'lolaperez@gmail.com', 'cont5678', 7, 1200, 'web/img/alumno1.jpg', 10),
('Raúl', 'González', 'raulitog@gmail.com', 'cont5678', 6, 1520, 'web/img/alumno2.jpg', 10),
('Elena', 'Rodríguez', 'e.rodriguez@gmail.com', 'cont5678', 4, 800, 'web/img/alumno3.jpg', 10),
('María', 'Alonso', 'maria.alonso@gmail.com', 'cont5678', 3, 1654, 'web/img/alumno4.jpg', 10),
('Roberto', 'García', 'robertoG@gmail.com', 'cont5678', 5, 1935, 'web/img/alumno5.jpg', 10);


INSERT INTO PROFE (NOMBRE_PROFE, APELLIDO_PROFE, EMAIL_PROFE, CONTRASENA_PROFE, IMG_PROFE, ID_CENTR) VALUES
('Alfonso', 'Muñoz', 'alfonsomuñoz@gmail.com', 'cont5678', 'web/img/profe1.jpg', 1),
('Emilia', 'HernÁndez', 'e.Hernandez@gmail.com', 'cont5678', 'web/img/profe2.jpg', 1),
('Gabriel', 'Márquez', 'gabrielMarquez@gmail.com', 'cont5678', 'web/img/profe3.jpg', 1),

('Isabel', 'Ordóñez', 'IsabelOrdoñez@gmail.com', 'cont5678', 'web/img/profe4.jpeg', 2),
('Laura', 'Cañizares', 'LauraCañizares@gmail.com', 'cont5678', 'web/img/profe5.jpg', 2),
('Saúl', 'Ortega', 'saul.ortega@gmail.com', 'cont5678', 'web/img/profe6.jpg', 2),

('César', 'García', 'cesargarcia@gmail.com', 'cont5678', 'web/img/profe7.jpg', 3),
('Manuel', 'Santamarta', 'm.Santamarta@gmail.com', 'cont5678', 'web/img/profe8.jpg', 3),
('Clara', 'Laguna', 'LagunaClara@gmail.com', 'cont5678', 'web/img/profe9.jpg', 3),
('Esteban', 'Calvo', 'estebancalvo@gmail.com', 'cont5678', 'web/img/profe10.jpg', 3);


INSERT INTO ASIGN (NOMBRE_ASIGN, ID_PROFE) VALUES
('Lengua castellana y literatura', 1),
('Inglés', 1),
('Matemáticas', 2),
('Biología y Geología', 2),
('Física y Química', 2),
('Ciencias Sociales', 3),
('Música', 3),
('Matemáticas', 4),
('Biología y Geología', 4),
('Lengua castellana y literatura', 5),
('Valores Éticos', 5),
('Matemáticas', 6),
('Tecnología', 6),
('Educación Física', 7),
('Biología y Geología', 7),
('Educación plástica y audiovisual', 8),
('Lengua Castellana y Literatura', 9),
('Latín', 9),
('Economía', 10),
('Matemáticas', 10),
('Educación para la ciudadanía', 10);


INSERT INTO TEMAS (NOMBRE_TEMAS, TRIMESTRE_TEMAS, ID_ASIGN) VALUES
/* LENGUA */
('El lenguaje literario', 1, 1),
('La narración, el lenguaje oral/ escrito, primitivas, derivadas y géneros literarios', 1, 1),
('Género nominal, sustantivos. Escribir carta y épica castellana', 1, 1),
('Descripción. Adjetivos, forma y uso', 1, 1),
('El lenguaje literario',1,1),
('La narración, lenguaje oral/escrito, primitivas, derivadas y géneros literarios',1,1),
('Género nominal, sustantivos. Escribir carta y épica castellana',1,1),
('Descripción. Adjetivos forma y uso',1,1),
('Verbo. Textos expositivos',1,1),
('Verbo. Cuento, novela y resumen',1,1),
('El determinante. Rima, verso, esquema',1,1),
('Pronombres. clasificación. Palabras compuestas. Lírica',1,1),
('Adverbio',1,1),
('Diálogo y sinónimos',1,1),
('Concepto de oración',1,1),
('Imperativas, desiderativas y dubitativas',1,1),

('El lenguaje y oración gramatical',1,1),
('El informe, los determinantes, función y clases. Lexemas y morfemas. Lírica',1,1),
('Los complementos, clases, sufijos. El folleto informativo. Lírica: la estrofa y el poema',1,1),
('Los pronombres. Clases. El texto instructivo. Lírica: serranilla, oda y el poema',1,1),
('El sintagma verbal. Formas. Morfemas flexivos. Los impresos. La épica',1,1),
('El predicado. Clases y complementos. El debate',1,1),
('El debate',1,1),
('La oración compuesta. Sinónima y antonimia. La coma y el guión y paréntesis. Teatro y las figuras literarias',1,1),

('Lengua y sociedad',1,1),
('Las palabras',1,1),
('La oración',1,1),
('Oración simple y compuesta',1,1),
('Clases de textos',1,1),
('La literatura',1,1),
('Edad Media',1,1),
('Siglo XV',1,1),
('El Renacimiento',1,1),
('El Barroco',1,1),
('El teatro',1,1),
('Siglo XVIII',1,1),

('El siglo XVIII: el Neoclasicismo',1,1), 
('Romanticismo',1,1), 
('Realismo',1,1),
('Modernismo',1,1),
('Generación del 98',1,1),
('Vanguardias',1,1), 
('Generación del 27',1,1), 

/* SOCIALES */
('Prehistoria: el Paleolítico',1,6),
('Neolítico y Edad de los metales',1,6),
('Mesopotamia y primeras civilizaciones',1,6),
('Antiguo Egipto',1,6),
('Grecia antigua',1,6),
('Roma antigua',1,6),
('Hispania romana',1,6),
('La Tierra en el universo',1,6),
('La representación de la Tierra y las coordenadas',1,6),
('Geografía física: relieve continental y océano mundial',1,6),
('Hidrografía: los ríos y el relieve',1,6),
('Tiempo y clima',1,6),
('Climas y paisajes naturales',1,6),
('Tiempo y clima en España',1,6),

('Imperio bizantino y carolingio',1,6),
('El Islam y el Al-Andalus',1,6),
('Cronología de la Edad Media',1,6),
('Las invasiones bárbaras',1,6),
('Carlomagno y su imperio',1,6),
('La Europa feudal',1,6),
('El renacer urbano de Europa',1,6), 
('Los descubrimientos',1,6),
('El nacimiento del Estado moderno',1,6), 
('El Renacimiento',1,6),
('Reforma y Contrarreforma',1,6),
('Los Reyes Católicos',1,6), 
('El arte renacentista',1,6),
('El siglo XVII',1,6),
('La población',1,6),

('El mapa físico de la Tierra',1,6),
('El mapa físico de España',1,6),
('La población en el mundo actual',1,6),
('Las ciudades en el mundo actual',1,6),
('La actividad económica y el trabajo',1,6),
('Las actividades del sector primario',1,6),
('Las actividades y los espacios industriales',1,6),
('Las actividades terciarias y su transformación',1,6),
('La economía de España',1,6),
('Los impactos medioambientales',1,6),
('La organización política de las sociedades',1,6),
('Desigualdades económicas y sociales',1,6),

('Introducción a la Historia',1,6),
('Los inicios del siglo XVIII',1,6),
('El liberalismo',1,6),
('Revolución Industrial',1,6), 
('España en el siglo XIX',1,6),
('Imperialismo y Primera Guerra Mundial',1,6),
('Periodo de entreguerras',1,6),
('España (1898-1975)',1,6),
('La Segunda Guerra Mundial',1,6),
('De la Guerra Fría al nuevo orden',1,6),
('La España reciente',1,6),
('Globalización y nuevo orden internacional',1,6),

/* MATEMÁTICAS */
('Números naturales',1,3),
('Divisibilidad',1,3),
('Números enteros',1,3),
('Números decimales',1,3),
('Fracciones',1,3),
('Proporcionalidad',1,3),
('Sistema métrico decimal',1,3),
('Elementos del plano',1,3),
('Polígonos',1,3),
('Áreas de las figuras planas',1,3),
('Circunferencia y círculo',1,3),
('Gráficas y funciones',1,3),

('Potencias y radicales',1,3),
('Fracciones',1,3),
('Números decimales',1,3),
('Proporcionalidad',1,3),
('Expresiones algebraicas',1,3),
('Ecuaciones',1,3), 
('Semejanza y teorema de Thales',1,3), 
('Volumen de cuerpos geométricos',1,3),
('Funciones',1,3),
('Estadística',1,3),

('Números reales',1,3),
('Potencias y radicales',1,3),
('Expresiones algebraicas',1,3),
('Ecuaciones',1,3),
('Sistema de ecuaciones',1,3),
('Sucesiones y progresiones',1,3),
('Concepto de función',1,3),
('Funciones elementales',1,3),
('Teoremas de Thales y Pitágoras',1,3),
('Problemas geométricos',1,3),
('Tablas y gráficos estadísticos',1,3),
('Parámetros estadísticos',1,3),
('Cálculo de probabilidades',1,3),
('Movimientos',1,3),

('Números reales',1,3),
('Radicales',1,3), 
('Polinomios y fracciones algebraicas',1,3),
('Ecuaciones y sistemas de ecuaciones no lineales',1,3),
('Inecuaciones',1,3),
('Conceptos básicos de funciones',1,3),
('Representación gráfica de parábolas e hipérbolas',1,3),
('Representar raíces, exponenciales y definidas a trozos',1,3),
('Estadística. Estudio de una variable',1,3),
('Combinatoria',1,3),
('Probabilidad. Conceptos básicos',1,3),
('Trigonometría: razones trigonométricas',1,3),
('Triángulos rectángulos',1,3),
('Vectores en el plano',1,3),
('Ecuaciones de la recta en el plana',1,3),

/* INGLÉS */
('Present simple',1,2),
('Present simple vs present continuos',1,2),
('This is/are',1,2),
('Quantifiers and uncountable',1,2),
('Adverbs of frequency',1,2),
('Questions words',1,2),
('Subject questions',1,2),
('Comparatives',1,2),
('Past simple',1,2),
('Irregular verbs',1,2),
('Modal verbs of obligation',1,2),
('Imperatives',1,2),
('Be going to',1,2),
('Present continuos with a future meaning',1,2),
('Will',1,2),
('Will or be going to',1,2),
('First conditonal',1,2),  

('Past simple and past continuos',1,2),
('Infinitive of purpose',1,2),
('Present simple and continuos with future meaning',1,2),
('Present continuos and be going to',1,2),
('Future: going to or will',1,2),
('Adjetives + prepositions',1,2),
('Adjetives: -ed y -ing',1,2),
('All, half, most and none',1,2),
('Enough and too',1,2),
('A few, few, a litlle and little',1,2),
('Present perfect: already, just, still and yet',1,2),
('Present perfect: for and since',1,2),
('Present perfect: been and gone',1,2),
('Present perfect: ever and never',1,2),
('First conditional',1,2),
('Second conditional',1,2),
('Modal verbs of ability',1,2),
('Modal verbs of obligation',1,2),
('Modal verbs of advice',1,2),
('Defining relative clauses',1,2),
('When to omit the relative pronoun',1,2),
('Phrasal verbs',1,2),
('Passive',1,2),

('Be and have got',1,2),
('Can/can not',1,2),
('Present continuos',1,2),
('Present simple',1,2),
('Present simple vs present continuos',1,2),
('Frequency adverbs',1,2),
('Past simple',1,2),
('Time expressions',1,2),
('Sequencing words',1,2),
('Past continuos',1,2),
('Past simple vs past continuos',1,2),
('Suggestions',1,2),
('Connectors',1,2),
('Have to',1,2),
('Some/any',1,2),
('Much/many/a lot of',1,2),
('Invitations',1,2),
('Comparatives + than',1,2),
('Superlatives + in',1,2),
('Too/enough + adjective',1,2),
('And y but',1,2),
('Prensent perfect affirmative and negative',1,2),
('Present perfect with just',1,2),
('Present perfect interrogative',1,2),
('Will',1,2),
('First condicional',1,2),

('Present simple vs present continuos',1,2),
('Like/enjoy/hate',1,2),
('Adverbs of frequency',1,2),
('Questions forms',1,2),
('Past simple',1,2),
('Past simple vs past continuos',1,2),
('Used to + infinitive',1,2),
('Connectors',1,2),
('Present perfect',1,2),
('For/since/just/already/yet',1,2),
('Present perfect vs past simple',1,2),
('Future with going to',1,2),
('Future with will',1,2),
('Future with present continuos',1,2),
('Expressing probability with may/might',1,2),
('Questions forms',1,2),
('Time clauses',1,2),
('First conditional',1,2),
('Unless',1,2),
('Adverbs of manner',1,2),
('Second conditional',1,2),
('Should/should not',1,2),
('Deffing relative clauses',1,2),
('The pasive',1,2),
('Reflexive pronouns',1,2),
('Reported speech',1,2),

/* EDUCACIÓN FISICA */
('Calentamiento general',1,14),
('Las capacidades físicas básicas',1,14),
('Habilidades motrices básicas',1,14),
('Iniciación al badminton',1,14),
('Iniciación al balonmano ',1,14),
('Iniciación a las técnicas de atletismo',1,14),

('Calentamientos motores',1,14),
('Nos ponemos en forma',1,14),
('Hábitos negativos',1,14),
('Quiero ser un buen deportista',1,14),
('Leer y exponer',1,14),
('Judo',1,14),
('Tenis',1,14),
('Jugamos otros deportes',1,14),
('El Circo del Sol',1,14),

('Ejercicio físico, condición física y salud',1,14),
('Frecuencia cardiaca',1,14),
('Calentamiento',1,14),
('Práctica de un deporte habitual',1,14),
('Juegos y deportes alternativos',1,14),
('Forma diferente de hacer gimnasia',1,14),
('Nutrición, salud y ejercicio físico',1,14),
('Respiración y relajación',1,14),

/* BIOLOGÍA Y GEOLOGÍA */
('La Tierra en el universo',1,4),
('La geosfera',1,4),
('Los minerales y las rocas',1,4),
('La atmósfera',1,4),
('La hidrosfera',1,4),
('La vida en la Tierra',1,4),
('Clasificación de los seres vivos',1,4),
('Invertebrados',1,4),
('Vertebrados',1,4),
('Las plantas',1,4),
('Los ecosistemas',1,4),
('Metodología científica',1,4),

('Organización general del cuerpo humano',1,6),
('Alimentación y salud',1,4),
('El aparato digestivo y la disgestión',1,4),
('El aparato respiratorio y la respiración',1,4),
('Aparato circulatorio y circulación',1,4), 
('El aparato excretor y la excreción',1,4),
('El sistema nervioso',1,4),
('El sistema endocrino',1,4),
('Órganos receptores. Órganos de los sentidos',1,4),
('Órganos efectores. Órganos de los sentidos',1,4), 
('Sexualidad y reproducción humanas',1,4), 
('La salud y la enfermedad',1,4), 
('Los ecosistemas',1,4), 
('La actividad geológica externa del planeta Tierra',1,4),
('La actividad geología interna del planeta Tierra',1,4), 

('El tiempo geológico',1,4), 
('Historia de la Tierra',1,4),
('La dinámica terrestre',1,4),
('La técnica de placas',1,4),
('La célula',1,4),
('La herencia genética',1,4),
('Genética humana',1,4),
('La ingeniería genética',1,4),
('Origen y evolución de los seres vivos',1,4),
('Dinámica de los ecosistemas',1,4),
('Dinámica de las comunidades',1,4),
('La humanidad y el medio ambiente',1,4),

/* MÚSICA */
('Introducción',1,7),
('La altura: definición y tipos de sonidos',1,7),
('El pentagrama y las notas musicales',1,7),
('La clave',1,7),
('Las líneas adicionales',1,7),
('Las alteraciones',1,7),

('El sonido y sus cualidades',1,7), 
('Elementos que intervienen en la audición',1,7),
('Las cuatro cualidades del sonido',1,7),
('La altura',1,7),
('La duración',1,7),
('La intensidad',1,7),
('El timbre',1,7),

/* VALORES ÉTICOS */
('La dignidad de la persona',1,11),
('La comprensión, el respeto y la igualdad en las relaciones humanas',1,11),
('La reflexión ética',1,11),
('Los valores éticos, el derecho y los derechos humanos',1,11),

('La dignidad de la persona',1,11), 
('Comprensión respeto e igualdad',1,11),
('La reflexión ética',1,11),
('Justicia y política',1,11),
('Derechos humanos',1,11), 
('Valores éticos, ciencia y tecnología',1,11),

/* FISICA Y QUIMICA */
('La actividad científica',1,5),
('Como trabajan los científicos',1,5),
('Estados de agregación',1,5),
('Los cambios en la materia',1,5),
('Formulación',1,5), 
('El movimiento y la fuerza',1,5),
('La energia',1,5), 

('Método científico',1,5),
('Estados de la materia y teoría científica',1,5),
('Sustancias puras y mezclas',1,5),
('El átomo y los elementos químicos',1,5),
('Los elementos y compuestos químicos',1,5),
('Reacciones químicas',1,5), 

('El movimiento rectilíneo',1,5),
('Movimiento circular',1,5),
('Las fuerzas',1,5),
('Fuerzas y presiones en fluidos',1,5),
('Astronomía y gravitación universal',1,5),
('Trabajo y energía',1,5),
('Calor y energía',1,5),
('Las ondas',1,5),
('Estructura de átomo y enlaces químicos',1,5),
('Transformación química',1,5),
('La química del carbono',1,5),
('Compuestos de carbono',1,5),

/* EDUCACIÓN PLÁSTICA Y AUDIOVISUAL */
('Lugares geométricos',1,16),
('Las texturas ',1,16),
('Tangencias',1,16),
('Relaciones entre formas ',1,16),
('Composiciones de formas modulares',1,16),
('El color',1,16),
('Diseño gráfico',1,16),

/* TECNOLOGÍA */
('Dibujo',1,13),
('La madera ',1,13),
('Metales',1,13),
('Estructuras',1,13),
('Electricidad',1,13),
('Informática',1,13),

/* LATÍN */
('El origen del latín y su diversificación',1,18),
('La lengua latina y su evolución',1,18),
('Introducción a la lengua latina',1,18),
('Primera declinación',1,18),
('Introducción a la flexión verbal',1,18),
('Segunda declinación y presente de indicativo',1,18),
('Historia de Roma y sus personajes',1,18),

/* ECONOMÍA */
('Ideas económicas básicas',1,19),
('Economía y empresa',1,19),
('Economía e ingresos y gastos del estado',1,19),
('Economía y tipos de interés, inflación y desempleo',1,19),
('Economía internacional',1,19),
('Economía personal',1,19),

/* EDUCACIÓN PARA LA CIUDADANÍA */
('La persona y su entorno',1,21),
('Barrios, pueblos y ciudades',1,21),
('Sociedades democráticas',1,21),
('Los derechos humanos',1,21),
('Un mundo globalizado, un mundo dividido',1,21),
('Hacia un mundo mejor',1,21);


INSERT INTO ENTRE (NOMBRE_ENTRE, DESCR_ENTRE, ID_TEMAS) VALUES
('Título de test de entrenamiento 1', 'Descripción de test de entrenamiento 1', 1),
('Título de test de entrenamiento 2', 'Descripción de test de entrenamiento 2', 13);

INSERT INTO FINAL (NOMBRE_FINAL, DESCR_FINAL, ID_TEMAS) VALUES
('Título de test de final', 'Descripción de test de final', 1);

INSERT INTO PREGU_ENTRE (ENUNCIADO_PREGU_ENTRE, ID_ENTRE) VALUES
('¿Qué escritor no pertenece a la Generación del 27?', 1),
('¿Qué es la Generación del 27?', 1),
('¿Quién escribió «La Colmena»?', 1),
('¿Qué escritora no es española?', 1),
('¿Qué libro no es del siglo XX?', 1),
('¿Cuál de estos libros no escribió Benito Pérez Galdós?', 1),
('¿Qué poema escribió Federico García Lorca?', 1),
('¿Qué escritora es la máxima representante del nturalismo en España?', 1),
('¿Cómo se llamaba la compañía teatral de Federico García Lorca?', 1),
('¿Quién escribió «Nada»?', 1),
('2 ¿Qué escritor no pertenece a la Generación del 27?', 2),
('2 ¿Qué es la Generación del 27?', 2),
('2 ¿Quién escribió «La Colmena»?', 2),
('2 ¿Qué escritora no es española?', 2),
('2 ¿Qué libro no es del siglo XX?', 2),
('2 ¿Cuál de estos libros no escribió Benito Pérez Galdós?', 2),
('2 ¿Qué poema escribió Federico García Lorca?', 2),
('2 ¿Qué escritora es la máxima representante del nturalismo en España?', 2),
('2 ¿Cómo se llamaba la compañía teatral de Federico García Lorca?', 2),
('2 ¿Quién escribió «Nada»?', 2);

INSERT INTO PREGU_FINAL (ENUNCIADO_PREGU_FINAL, ID_FINAL) VALUES
('FINAL ¿Qué escritor no pertenece a la Generación del 27?', 1),
('FINAL ¿Qué es la Generación del 27?', 1),
('FINAL ¿Quién escribió «La Colmena»?', 1),
('FINAL ¿Qué escritora no es española?', 1),
('FINAL ¿Qué libro no es del siglo XX?', 1),
('FINAL ¿Cuál de estos libros no escribió Benito Pérez Galdós?', 1),
('FINAL ¿Qué poema escribió Federico García Lorca?', 1),
('FINAL ¿Qué escritora es la máxima representante del nturalismo en España?', 1),
('FINAL ¿Cómo se llamaba la compañía teatral de Federico García Lorca?', 1),
('FINAL ¿Quién escribió «Nada»?', 1);

INSERT INTO RESPU_ENTRE (TEXTO_RESPU_ENTRE, PESO_RESPU_ENTRE, CORRECTA_RESPUE_ENTRE, ID_PREGU_ENTRE) VALUES
('Respuesta 1', 1, 0, 1),
('Respuesta 2', 2, 0, 1),
('Respuesta 3', 3, 0, 1),
('Respuesta 4', 4, 1, 1),
('Respuesta 1', 1, 0, 2),
('Respuesta 2', 2, 0, 2),
('Respuesta 3', 3, 0, 2),
('Respuesta 4', 4, 1, 2),
('Respuesta 1', 1, 0, 3),
('Respuesta 2', 2, 0, 3),
('Respuesta 3', 3, 0, 3),
('Respuesta 4', 4, 1, 3),
('Respuesta 1', 1, 0, 4),
('Respuesta 2', 2, 0, 4),
('Respuesta 3', 3, 0, 4),
('Respuesta 4', 4, 1, 4),
('Respuesta 1', 1, 0, 5),
('Respuesta 2', 2, 0, 5),
('Respuesta 3', 3, 0, 5),
('Respuesta 4', 4, 1, 5),
('Respuesta 1', 1, 0, 6),
('Respuesta 2', 2, 0, 6),
('Respuesta 3', 3, 0, 6),
('Respuesta 4', 4, 1, 6),
('Respuesta 1', 1, 0, 7),
('Respuesta 2', 2, 0, 7),
('Respuesta 3', 3, 0, 7),
('Respuesta 4', 4, 1, 7),
('Respuesta 1', 1, 0, 8),
('Respuesta 2', 2, 0, 8),
('Respuesta 3', 3, 0, 8),
('Respuesta 4', 4, 1, 8),
('Respuesta 1', 1, 0, 9),
('Respuesta 2', 2, 0, 9),
('Respuesta 3', 3, 0, 9),
('Respuesta 4', 4, 1, 9),
('Respuesta 1', 1, 0, 10),
('Respuesta 2', 2, 0, 10),
('Respuesta 3', 3, 0, 10),
('Respuesta 4', 4, 1, 10),
('Respuesta 1', 1, 0, 11),
('Respuesta 2', 2, 0, 11),
('Respuesta 3', 3, 0, 11),
('Respuesta 4', 4, 1, 11),
('Respuesta 1', 1, 0, 12),
('Respuesta 2', 2, 0, 12),
('Respuesta 3', 3, 0, 12),
('Respuesta 4', 4, 1, 12),
('Respuesta 1', 1, 0, 13),
('Respuesta 2', 2, 0, 13),
('Respuesta 3', 3, 0, 13),
('Respuesta 4', 4, 1, 13),
('Respuesta 1', 1, 0, 14),
('Respuesta 2', 2, 0, 14),
('Respuesta 3', 3, 0, 14),
('Respuesta 4', 4, 1, 14),
('Respuesta 1', 1, 0, 15),
('Respuesta 2', 2, 0, 15),
('Respuesta 3', 3, 0, 15),
('Respuesta 4', 4, 1, 15),
('Respuesta 1', 1, 0, 16),
('Respuesta 2', 2, 0, 16),
('Respuesta 3', 3, 0, 16),
('Respuesta 4', 4, 1, 16),
('Respuesta 1', 1, 0, 17),
('Respuesta 2', 2, 0, 17),
('Respuesta 3', 3, 0, 17),
('Respuesta 4', 4, 1, 17),
('Respuesta 1', 1, 0, 18),
('Respuesta 2', 2, 0, 18),
('Respuesta 3', 3, 0, 18),
('Respuesta 4', 4, 1, 18),
('Respuesta 1', 1, 0, 19),
('Respuesta 2', 2, 0, 19),
('Respuesta 3', 3, 0, 19),
('Respuesta 4', 4, 1, 19),
('Respuesta 1', 1, 0, 20),
('Respuesta 2', 2, 0, 20),
('Respuesta 3', 3, 0, 20),
('Respuesta 4', 4, 1, 20);

INSERT INTO RESPU_FINAL (TEXTO_RESPU_FINAL, PESO_RESPU_FINAL, CORRECTA_RESPUE_FINAL, ID_PREGU_FINAL) VALUES
('Respuesta 1', 1, 0, 1),
('Respuesta 2', 2, 0, 1),
('Respuesta 3', 3, 0, 1),
('Respuesta 4', 4, 1, 1),
('Respuesta 1', 1, 0, 2),
('Respuesta 2', 2, 0, 2),
('Respuesta 3', 3, 0, 2),
('Respuesta 4', 4, 1, 2),
('Respuesta 1', 1, 0, 3),
('Respuesta 2', 2, 0, 3),
('Respuesta 3', 3, 0, 3),
('Respuesta 4', 4, 1, 3),
('Respuesta 1', 1, 0, 4),
('Respuesta 2', 2, 0, 4),
('Respuesta 3', 3, 0, 4),
('Respuesta 4', 4, 1, 4),
('Respuesta 1', 1, 0, 5),
('Respuesta 2', 2, 0, 5),
('Respuesta 3', 3, 0, 5),
('Respuesta 4', 4, 1, 5),
('Respuesta 1', 1, 0, 6),
('Respuesta 2', 2, 0, 6),
('Respuesta 3', 3, 0, 6),
('Respuesta 4', 4, 1, 6),
('Respuesta 1', 1, 0, 7),
('Respuesta 2', 2, 0, 7),
('Respuesta 3', 3, 0, 7),
('Respuesta 4', 4, 1, 7),
('Respuesta 1', 1, 0, 8),
('Respuesta 2', 2, 0, 8),
('Respuesta 3', 3, 0, 8),
('Respuesta 4', 4, 1, 8),
('Respuesta 1', 1, 0, 9),
('Respuesta 2', 2, 0, 9),
('Respuesta 3', 3, 0, 9),
('Respuesta 4', 4, 1, 9),
('Respuesta 1', 1, 0, 10),
('Respuesta 2', 2, 0, 10),
('Respuesta 3', 3, 0, 10),
('Respuesta 4', 4, 1, 10);

INSERT INTO REL_GRUPO_ASIGN (ID_GRUPO, ID_ASIGN) VALUES
(1, 1),
(1, 2),
(2, 1),
(2, 2);

INSERT INTO REL_ALUMN_ENTRE (FECHA_REL_ALUMN_ENTRE, ID_ALUMN, ID_ENTRE) VALUES
(DATE('2017-11-01'), 1, 1);

INSERT INTO REL_ALUMN_FINAL (FECHA_REL_ALUMN_FINAL, PUNTOS_REL_ALUMN_FINAL, ID_ALUMN, ID_FINAL) VALUES
(DATE('2017-11-01'),430, 1, 1);
