 CREATE DATABASE IF NOT EXISTS DBLEARN DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

USE DBLEARN;

CREATE TABLE IF NOT EXISTS CENTR (

	ID_CENTR INT NOT NULL AUTO_INCREMENT PRIMARY KEY,

	NOMBRE_CENTR VARCHAR (50) CHARACTER SET utf8,

	COMUNIDAD_CENTR VARCHAR (40) CHARACTER SET utf8,

	MUNICIPIO_CENTR VARCHAR (40) CHARACTER SET utf8,

	CP_CENTR SMALLINT (5)

)ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;


CREATE TABLE IF NOT EXISTS PROFE (

	ID_PROFE INT NOT NULL AUTO_INCREMENT PRIMARY KEY,

	NOMBRE_PROFE VARCHAR (40) CHARACTER SET utf8,

	APELLIDO_PROFE VARCHAR (100) CHARACTER SET utf8,

	EMAIL_PROFE VARCHAR (100) CHARACTER SET utf8,

	CONTRASENA_PROFE VARCHAR (8) CHARACTER SET utf8,

	IMG_PROFE VARCHAR (120) CHARACTER SET utf8,

	ID_CENTR INT,

	FOREIGN KEY (ID_CENTR) REFERENCES CENTR (ID_CENTR)

)ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;


CREATE TABLE IF NOT EXISTS CURSO (

	ID_CURSO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,

	NIVEL_CURSO VARCHAR (20) CHARACTER SET utf8,

	ID_CENTR INT,

	FOREIGN KEY (ID_CENTR) REFERENCES CENTR (ID_CENTR)

)ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;


CREATE TABLE IF NOT EXISTS ASIGN (

	ID_ASIGN INT NOT NULL AUTO_INCREMENT PRIMARY KEY,

	NOMBRE_ASIGN VARCHAR (100) CHARACTER SET utf8,

	ID_PROFE INT,

	FOREIGN KEY (ID_PROFE) REFERENCES PROFE (ID_PROFE)

)ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;


CREATE TABLE IF NOT EXISTS TEMAS (

	ID_TEMAS INT NOT NULL AUTO_INCREMENT PRIMARY KEY,

	NOMBRE_TEMAS TEXT CHARACTER SET utf8,

	ICON_TEMAS VARCHAR (120) CHARACTER SET utf8,

	TRIMESTRE_TEMAS VARCHAR(1) CHARACTER SET utf8,

	ID_ASIGN INT,

	FOREIGN KEY (ID_ASIGN) REFERENCES ASIGN (ID_ASIGN)

)ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;


CREATE TABLE IF NOT EXISTS GRUPO (

	ID_GRUPO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,

	LETRA_GRUPO VARCHAR (1) CHARACTER SET utf8,

	ID_CURSO INT,

	FOREIGN KEY (ID_CURSO) REFERENCES CURSO (ID_CURSO)

)ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;


CREATE TABLE IF NOT EXISTS REL_GRUPO_ASIGN (
	ID_GRUPO INT,

	ID_ASIGN INT,

	FOREIGN KEY (ID_GRUPO) REFERENCES GRUPO (ID_GRUPO),

	FOREIGN KEY (ID_ASIGN) REFERENCES ASIGN (ID_ASIGN)

)ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;


CREATE TABLE IF NOT EXISTS ALUMN (

	ID_ALUMN INT NOT NULL AUTO_INCREMENT PRIMARY KEY,

	NOMBRE_ALUMN VARCHAR (40) CHARACTER SET utf8,

	APELLIDO_ALUMN VARCHAR (100) CHARACTER SET utf8,

	EMAIL_ALUMN VARCHAR (100) CHARACTER SET utf8,

	CONTRASENA_ALUMN VARCHAR (8) CHARACTER SET utf8,

	EXPERIENCIA_ALUMN INT,

	PUNTOS_ALUMN INT,

  	IMG_ALUMN VARCHAR (120) CHARACTER SET utf8,

	ID_GRUPO INT,

	FOREIGN KEY (ID_GRUPO) REFERENCES GRUPO (ID_GRUPO)

)ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;


CREATE TABLE IF NOT EXISTS FINAL (

	ID_FINAL INT NOT NULL AUTO_INCREMENT PRIMARY KEY,

	NOMBRE_FINAL VARCHAR (200) CHARACTER SET utf8,

	DESCR_FINAL TEXT CHARACTER SET utf8,

	ID_TEMAS INT,

	FOREIGN KEY (ID_TEMAS) REFERENCES TEMAS (ID_TEMAS)

)ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;


CREATE TABLE IF NOT EXISTS ENTRE (

	ID_ENTRE INT NOT NULL AUTO_INCREMENT PRIMARY KEY,

	NOMBRE_ENTRE VARCHAR (200) CHARACTER SET utf8,

	DESCR_ENTRE TEXT CHARACTER SET utf8,

	ID_TEMAS INT,

	FOREIGN KEY (ID_TEMAS) REFERENCES TEMAS (ID_TEMAS)

)ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;


CREATE TABLE IF NOT EXISTS REL_ALUMN_ENTRE (

	ID_REL_ALUMN_ENTRE INT NOT NULL AUTO_INCREMENT PRIMARY KEY,

	FECHA_REL_ALUMN_ENTRE DATE,

	ID_ALUMN INT,

	ID_ENTRE INT,

	FOREIGN KEY (ID_ALUMN) REFERENCES ALUMN (ID_ALUMN),

	FOREIGN KEY (ID_ENTRE) REFERENCES ENTRE (ID_ENTRE)

)ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;


CREATE TABLE IF NOT EXISTS REL_ALUMN_FINAL (

	ID_REL_ALUMN_FINAL INT NOT NULL AUTO_INCREMENT PRIMARY KEY,

	PUNTOS_REL_ALUMN_FINAL INT,

	ID_ALUMN INT,

	ID_FINAL INT,

	FOREIGN KEY (ID_ALUMN) REFERENCES ALUMN (ID_ALUMN),

	FOREIGN KEY (ID_FINAL) REFERENCES FINAL (ID_FINAL)

)ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;


CREATE TABLE IF NOT EXISTS PREGU_ENTRE (

	ID_PREGU_ENTRE INT NOT NULL AUTO_INCREMENT PRIMARY KEY,

	ENUNCIADO_PREGU_ENTRE TEXT CHARACTER SET utf8,

	ID_ENTRE INT,

	FOREIGN KEY (ID_ENTRE) REFERENCES ENTRE (ID_ENTRE)


)ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;


CREATE TABLE IF NOT EXISTS PREGU_FINAL (

	ID_PREGU_FINAL INT NOT NULL AUTO_INCREMENT PRIMARY KEY,

	ENUNCIADO_PREGU_FINAL TEXT CHARACTER SET utf8,

	ID_FINAL INT,

	FOREIGN KEY (ID_FINAL) REFERENCES FINAL (ID_FINAL)

)ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;


CREATE TABLE IF NOT EXISTS RESPU_ENTRE (

	ID_RESPU_ENTRE INT NOT NULL AUTO_INCREMENT PRIMARY KEY,

	TEXTO_RESPU_ENTRE TEXT CHARACTER SET utf8,

	PESO_RESPU_ENTRE TINYINT,

	CORRECTA_RESPUE_ENTRE BIT,

	ID_PREGU_ENTRE INT,

	FOREIGN KEY (ID_PREGU_ENTRE) REFERENCES PREGU_ENTRE (ID_PREGU_ENTRE)

)ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;


CREATE TABLE IF NOT EXISTS RESPU_FINAL (

	ID_RESPU_FINAL INT NOT NULL AUTO_INCREMENT PRIMARY KEY,

	TEXTO_RESPU_FINAL TEXT CHARACTER SET utf8,

	PESO_RESPU_FINAL TINYINT,

	CORRECTA_RESPUE_FINAL BIT,

	ID_PREGU_FINAL INT,

	FOREIGN KEY (ID_PREGU_FINAL) REFERENCES PREGU_FINAL (ID_PREGU_FINAL)

)ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

INSERT INTO CENTR (NOMBRE_CENTR, COMUNIDAD_CENTR, MUNICIPIO_CENTR, CP_CENTR) VALUES
('I.E.S. Mariano Quintanilla', 'Comunidad de Madrid', 'Madrid', 28015);

INSERT INTO CURSO (NIVEL_CURSO, ID_CENTR) VALUES
('1º E. S. O.', 1);

INSERT INTO GRUPO (LETRA_GRUPO, ID_CURSO) VALUES
('A', 1);

INSERT INTO ALUMN (NOMBRE_ALUMN, APELLIDO_ALUMN, EMAIL_ALUMN, CONTRASENA_ALUMN, EXPERIENCIA_ALUMN, PUNTOS_ALUMN, IMG_ALUMN, ID_GRUPO) VALUES
('Lola', 'Flores', 'lolaflores@email.com', '12345678', 250, 1230, 'web/img/lolaflores.jpg', 1);

INSERT INTO PROFE (NOMBRE_PROFE, APELLIDO_PROFE, EMAIL_PROFE, CONTRASENA_PROFE, IMG_PROFE, ID_CENTR) VALUES
('Lola', 'Flores', 'lolaflores@email.com','12345678', 'web/img/lolaflores.jpg', 1);

INSERT INTO ASIGN (NOMBRE_ASIGN, ID_PROFE) VALUES
('Lengua y literatura', 1);

INSERT INTO TEMAS (NOMBRE_TEMAS, TRIMESTRE_TEMAS, ID_ASIGN) VALUES
('La novela contemporánea', 1, 1);

INSERT INTO ENTRE (NOMBRE_ENTRE, DESCR_ENTRE, ID_TEMAS) VALUES
('Título de test de entrenamiento', 'Descripción de test de entrenamiento', 1);

INSERT INTO FINAL (NOMBRE_FINAL, DESCR_FINAL, ID_TEMAS) VALUES
('Título de test de final', 'Descripción de test de final', 1);

INSERT INTO PREGU_ENTRE (ENUNCIADO_PREGU_ENTRE, ID_ENTRE) VALUES
('¿Qué escritor no pertenece a la Generación del 27?', 1),
('¿Qué es la Generación del 27?', 1),
('¿Quién escribió «La Colmena»?', 1),
('¿Qué escritora no es española?', 1),
('¿Qué libro no es del siglo XX?', 1),
('¿Cuál de estos libros no escribió Benito Pérez Galdós?', 1),
('¿Qué poema escribió Federico García Lorca?', 1),
('¿Qué escritora es la máxima representante del nturalismo en España?', 1),
('¿Cómo se llamaba la compañía teatral de Federico García Lorca?', 1),
('¿Quién escribió «Nada»?', 1);

INSERT INTO PREGU_FINAL (ENUNCIADO_PREGU_FINAL, ID_FINAL) VALUES
('FINAL ¿Qué escritor no pertenece a la Generación del 27?', 1),
('FINAL ¿Qué es la Generación del 27?', 1),
('FINAL ¿Quién escribió «La Colmena»?', 1),
('FINAL ¿Qué escritora no es española?', 1),
('FINAL ¿Qué libro no es del siglo XX?', 1),
('FINAL ¿Cuál de estos libros no escribió Benito Pérez Galdós?', 1),
('FINAL ¿Qué poema escribió Federico García Lorca?', 1),
('FINAL ¿Qué escritora es la máxima representante del nturalismo en España?', 1),
('FINAL ¿Cómo se llamaba la compañía teatral de Federico García Lorca?', 1),
('FINAL ¿Quién escribió «Nada»?', 1);

INSERT INTO RESPU_ENTRE (TEXTO_RESPU_ENTRE, PESO_RESPU_ENTRE, CORRECTA_RESPUE_ENTRE, ID_PREGU_ENTRE) VALUES
('Respuesta 1', 1, 0, 1),
('Respuesta 2', 2, 0, 1),
('Respuesta 3', 3, 0, 1),
('Respuesta 4', 4, 1, 1),
('Respuesta 1', 1, 0, 2),
('Respuesta 2', 2, 0, 2),
('Respuesta 3', 3, 0, 2),
('Respuesta 4', 4, 1, 2),
('Respuesta 1', 1, 0, 3),
('Respuesta 2', 2, 0, 3),
('Respuesta 3', 3, 0, 3),
('Respuesta 4', 4, 1, 3),
('Respuesta 1', 1, 0, 4),
('Respuesta 2', 2, 0, 4),
('Respuesta 3', 3, 0, 4),
('Respuesta 4', 4, 1, 4),
('Respuesta 1', 1, 0, 5),
('Respuesta 2', 2, 0, 5),
('Respuesta 3', 3, 0, 5),
('Respuesta 4', 4, 1, 5),
('Respuesta 1', 1, 0, 6),
('Respuesta 2', 2, 0, 6),
('Respuesta 3', 3, 0, 6),
('Respuesta 4', 4, 1, 6),
('Respuesta 1', 1, 0, 7),
('Respuesta 2', 2, 0, 7),
('Respuesta 3', 3, 0, 7),
('Respuesta 4', 4, 1, 7),
('Respuesta 1', 1, 0, 8),
('Respuesta 2', 2, 0, 8),
('Respuesta 3', 3, 0, 8),
('Respuesta 4', 4, 1, 8),
('Respuesta 1', 1, 0, 9),
('Respuesta 2', 2, 0, 9),
('Respuesta 3', 3, 0, 9),
('Respuesta 4', 4, 1, 9),
('Respuesta 1', 1, 0, 10),
('Respuesta 2', 2, 0, 10),
('Respuesta 3', 3, 0, 10),
('Respuesta 4', 4, 1, 10);

INSERT INTO RESPU_FINAL (TEXTO_RESPU_FINAL, PESO_RESPU_FINAL, CORRECTA_RESPUE_FINAL, ID_PREGU_FINAL) VALUES
('Respuesta 1', 1, 0, 1),
('Respuesta 2', 2, 0, 1),
('Respuesta 3', 3, 0, 1),
('Respuesta 4', 4, 1, 1),
('Respuesta 1', 1, 0, 2),
('Respuesta 2', 2, 0, 2),
('Respuesta 3', 3, 0, 2),
('Respuesta 4', 4, 1, 2),
('Respuesta 1', 1, 0, 3),
('Respuesta 2', 2, 0, 3),
('Respuesta 3', 3, 0, 3),
('Respuesta 4', 4, 1, 3),
('Respuesta 1', 1, 0, 4),
('Respuesta 2', 2, 0, 4),
('Respuesta 3', 3, 0, 4),
('Respuesta 4', 4, 1, 4),
('Respuesta 1', 1, 0, 5),
('Respuesta 2', 2, 0, 5),
('Respuesta 3', 3, 0, 5),
('Respuesta 4', 4, 1, 5),
('Respuesta 1', 1, 0, 6),
('Respuesta 2', 2, 0, 6),
('Respuesta 3', 3, 0, 6),
('Respuesta 4', 4, 1, 6),
('Respuesta 1', 1, 0, 7),
('Respuesta 2', 2, 0, 7),
('Respuesta 3', 3, 0, 7),
('Respuesta 4', 4, 1, 7),
('Respuesta 1', 1, 0, 8),
('Respuesta 2', 2, 0, 8),
('Respuesta 3', 3, 0, 8),
('Respuesta 4', 4, 1, 8),
('Respuesta 1', 1, 0, 9),
('Respuesta 2', 2, 0, 9),
('Respuesta 3', 3, 0, 9),
('Respuesta 4', 4, 1, 9),
('Respuesta 1', 1, 0, 10),
('Respuesta 2', 2, 0, 10),
('Respuesta 3', 3, 0, 10),
('Respuesta 4', 4, 1, 10);

INSERT INTO REL_GRUPO_ASIGN (ID_GRUPO, ID_ASIGN) VALUES
(1, 1);

INSERT INTO REL_ALUMN_ENTRE (FECHA_REL_ALUMN_ENTRE, ID_ALUMN, ID_ENTRE) VALUES
(DATE('2017-11-01'), 1, 1);

INSERT INTO REL_ALUMN_FINAL (PUNTOS_REL_ALUMN_FINAL, ID_ALUMN, ID_FINAL) VALUES
(430, 1, 1);