 CREATE DATABASE IF NOT EXISTS DBLEARN DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

USE DBLEARN;

CREATE TABLE IF NOT EXISTS PROFE (

	ID_PROFE INT NOT NULL AUTO_INCREMENT PRIMARY KEY,

	NOMBRE_PROFE VARCHAR (40) CHARACTER SET utf8,

	APELLIDO_PROFE VARCHAR (100) CHARACTER SET utf8,

	EMAIL_PROFE VARCHAR (100) CHARACTER SET utf8,

	CONTRASENA_PROFE VARCHAR (8) CHARACTER SET utf8,

	IMG_PROFE VARCHAR (120) CHARACTER SET utf8,

	ID_CENTR INT,

	FOREIGN KEY (ID_CENTR) REFERENCES CENTR (ID_CENTR)

)ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;


CREATE TABLE IF NOT EXISTS CENTR (

	ID_CENTR INT NOT NULL AUTO_INCREMENT PRIMARY KEY,

	NOMBRE_CENTR VARCHAR (50) CHARACTER SET utf8,

	COMUNIDAD_CENTR VARCHAR (40) CHARACTER SET utf8,

	MUNICIPIO_CENTR VARCHAR (40) CHARACTER SET utf8,

	CP_CENTR SMALLINT (5)

)ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;


CREATE TABLE IF NOT EXISTS CURSO (

	ID_CURSO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,

	NIVEL_CURSO VARCHAR (20) CHARACTER SET utf8,

	ID_CENTR INT,

	FOREIGN KEY (ID_CENTR) REFERENCES CENTR (ID_CENTR)

)ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;


CREATE TABLE IF NOT EXITS ASIGN {

	ID_ASIGN INT NOT NULL AUTO_INCREMENT PRIMARY KEY,

	NOMBRE_ASIGN VARCHAR (100) CHARACTER SET utf8,

	ID_PROFE INT,

	FOREIGN KEY (ID_PROFE) REFERENCES PROFE (ID_PROFE)

}ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;


CREATE TABLE IF NOT EXITS TEMAS {

	ID_TEMAS INT NOT NULL AUTO_INCREMENT PRIMARY KEY,

	NOMBRE_TEMAS TEXT CHARACTER SET utf8,

	ICON_TEMAS VARCHAR (120) CHARACTER SET utf8,

	TRIMESTRE_TEMAS VARCHAR(1) CHARACTER SET utf8,

	ID_ASIGN INT,

	FOREIGN KEY (ID_ASIGN) REFERENCES ASIGN (ID_ASIGN)

}ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;


CREATE TABLE IF NOT EXISTS GRUPO (

	ID_GRUPO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,

	LETRA_GRUPO VARCHAR (1) CHARACTER SET utf8,

	ID_CURSO INT,

	FOREIGN KEY (ID_CURSO) REFERENCES CURSO (ID_CURSO)

)ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;


CREATE TABLE IF NOT EXITS REL_GRUPO_ASIGN {
	ID_GRUPO INT,

	ID_ASIGN INT,

	FOREIGN KEY (ID_GRUPO) REFERENCES GRUPO (ID_GRUPO),

	FOREIGN KEY (ID_ASIGN) REFERENCES ASIGN (ID_ASIGN)

}ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;


CREATE TABLE IF NOT EXISTS ALUMN (

	ID_ALUMN INT NOT NULL AUTO_INCREMENT PRIMARY KEY,

	NOMBRE_ALUMN VARCHAR (40) CHARACTER SET utf8,

	APELLIDO_ALUMN VARCHAR (100) CHARACTER SET utf8,

	EMAIL_ALUMN VARCHAR (100) CHARACTER SET utf8,

	CONTRASENA_ALUMN VARCHAR (8) CHARACTER SET utf8,

	EXPERIENCIA_ALUMN INT,

	PUNTOS_ALUMN INT,

  	IMG_ALUMN VARCHAR (120) CHARACTER SET utf8,

	ID_GRUPO INT,

	FOREIGN KEY (ID_GRUPO) REFERENCES GRUPO (ID_GRUPO)

)ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;


CREATE TABLE IF NOT EXITS FINAL {

	ID_FINAL INT NOT NULL AUTO_INCREMENT PRIMARY KEY,

	NOMBRE_FINAL VARCHAR (200) CHARACTER SET utf8,

	DESCR_FINAL TEXT CHARACTER SET utf8,

	ID_TEMAS INT,

	FOREIGN KEY (ID_TEMAS) REFERENCES TEMAS (ID_TEMAS)

}ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;


CREATE TABLE IF NOT EXITS ENTRE {

	ID_ENTRE INT NOT NULL AUTO_INCREMENT PRIMARY KEY,

	NOMBRE_ENTRE VARCHAR (200) CHARACTER SET utf8,

	DESCR_ENTRE TEXT CHARACTER SET utf8,

	ID_TEMAS INT,

	FOREIGN KEY (ID_TEMAS) REFERENCES TEMAS (ID_TEMAS)

}ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;


CREATE TABLE IF NOT EXITS REL_ALUMN_ENTRE {

	ID_REL_ALUMN_ENTRE INT NOT NULL AUTO_INCREMENT PRIMARY KEY,

	FECHA_REL_ALUMN_ENTRE DATE,

	ID_ALUMN INT,

	ID_ENTRE INT,

	FOREIGN KEY (ID_ALUMN) REFERENCES ALUMN (ID_ALUMN),

	FOREIGN KEY (ID_ENTRE) REFERENCES ENTRE (ID_ENTRE)

}ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;


CREATE TABLE IF NOT EXITS REL_ALUMN_FINAL {

	ID_REL_ALUMN_FINAL INT NOT NULL AUTO_INCREMENT PRIMARY KEY,

	PUNTOS_REL_ALUMN_FINAL INT,

	ID_ALUMN INT,

	ID_FINAL INT,

	FOREIGN KEY (ID_ALUMN) REFERENCES ALUMN (ID_ALUMN),

	FOREIGN KEY (ID_FINAL) REFERENCES FINAL (ID_FINAL)

}ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;


CREATE TABLE IF NOT EXISTS PREGU_ENTRE (

	ID_PREGU_ENTRE INT NOT NULL AUTO_INCREMENT PRIMARY KEY,

	ENUNCIADO_PREGU_ENTRE TEXT CHARACTER SET utf8,

	ID_ENTRE INT,

	FOREIGN KEY (ID_ENTRE) REFERENCES ENTRE (ID_ENTRE)


)ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;


CREATE TABLE IF NOT EXISTS PREGU_FINAL (

	ID_PREGU_FINAL INT NOT NULL AUTO_INCREMENT PRIMARY KEY,

	ENUNCIADO_PREGU_FINAL TEXT CHARACTER SET utf8,

	ID_FINAL INT,

	FOREIGN KEY (ID_FINAL) REFERENCES FINAL (ID_FINAL)

)ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;


CREATE TABLE IF NOT EXISTS RESPU_ENTRE (

	ID_RESPU_ENTRE INT NOT NULL AUTO_INCREMENT PRIMARY KEY,

	TEXTO_RESPU_ENTRE TEXT CHARACTER SET utf8,

	PESO_RESPU_ENTRE TINYINT,

	CORRECTA_RESPUE_ENTRE BIT,

	ID_PREGU_ENTRE INT,

	FOREIGN KEY (ID_PREGU_ENTRE) REFERENCES PREGU_ENTRE (ID_PREGU_ENTRE)

)ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;


CREATE TABLE IF NOT EXISTS RESPU_FINAL (

	ID_RESPU_FINAL INT NOT NULL AUTO_INCREMENT PRIMARY KEY,

	TEXTO_RESPU_FINAL TEXT CHARACTER SET utf8,

	PESO_RESPU_FINAL TINYINT,

	CORRECTA_RESPUE_FINAL BIT,

	ID_PREGU_FINAL INT,

	FOREIGN KEY (ID_PREGU_FINAL) REFERENCES PREGU_FINAL (ID_PREGU_FINAL)

)ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
